// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.ReportEngine.Models.Reports
{
    public partial class ReportActionSetting
    {
        public int ActionId { get; set; }
        public string ReportName { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}