// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class AuthorisationStatus
    {
        public AuthorisationStatus()
        {
            POPOrderReturnArches = new HashSet<POPOrderReturnArch>();
            POPOrderReturns = new HashSet<POPOrderReturn>();
        }

        public long AuthorisationStatusID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<POPOrderReturnArch> POPOrderReturnArches { get; set; }
        public virtual ICollection<POPOrderReturn> POPOrderReturns { get; set; }
    }
}