// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class Authoriser
    {
        public Authoriser()
        {
            InverseAuthoriserParent = new HashSet<Authoriser>();
        }

        public long AuthoriserID { get; set; }
        public long AuthoriserTypeID { get; set; }
        public long ItemID { get; set; }
        public long UserID { get; set; }
        public string AuthoriserName { get; set; }
        public long? AlternativeAuthoriserID { get; set; }
        public long? AuthoriserParentID { get; set; }
        public long AuthorisationGroup { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual Authoriser AuthoriserParent { get; set; }
        public virtual AuthoriserType AuthoriserType { get; set; }
        public virtual ICollection<Authoriser> InverseAuthoriserParent { get; set; }
    }
}