// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class BLClause
    {
        public BLClause()
        {
            BLBillTemplateClauses = new HashSet<BLBillTemplateClause>();
            BLClauseAttributes = new HashSet<BLClauseAttribute>();
            BLClauseEvents = new HashSet<BLClauseEvent>();
        }

        public long BLClauseID { get; set; }
        public long? PCCostItemTypeID { get; set; }
        public string NominalAccountNumber { get; set; }
        public string NominalCostCentre { get; set; }
        public string NominalDepartment { get; set; }
        public long? TaxCodeID { get; set; }
        public long? BLDetailOrSummaryTypeID { get; set; }
        public string BLClauseTypeKey { get; set; }
        public long? PCCostItemID { get; set; }
        public bool IncludeNegativeEntries { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public string Narrative { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BLDetailOrSummaryType BLDetailOrSummaryType { get; set; }
        public virtual PCCostItem PCCostItem { get; set; }
        public virtual PCCostItemType PCCostItemType { get; set; }
        public virtual ICollection<BLBillTemplateClause> BLBillTemplateClauses { get; set; }
        public virtual ICollection<BLClauseAttribute> BLClauseAttributes { get; set; }
        public virtual ICollection<BLClauseEvent> BLClauseEvents { get; set; }
    }
}