// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class BomBuildSessionStatus
    {
        public BomBuildSessionStatus()
        {
            BomBuildSessions = new HashSet<BomBuildSession>();
        }

        public long BomBuildSessionStatusID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<BomBuildSession> BomBuildSessions { get; set; }
    }
}