// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class BomCostSession
    {
        public BomCostSession()
        {
            BomCostSessionTotals = new HashSet<BomCostSessionTotal>();
            BomCosts = new HashSet<BomCost>();
        }

        public long BomCostSessionID { get; set; }
        public long BomRecordID { get; set; }
        public long BomBuildPackageID { get; set; }
        public long? CheckedOutBomBuildPackageID { get; set; }
        public string BomReference { get; set; }
        public long BomVersionStatusID { get; set; }
        public string BomVersion { get; set; }
        public string UserRevisionNumber { get; set; }
        public string CostedBy { get; set; }
        public DateTime DateTimeCosted { get; set; }
        public decimal QtyCosted { get; set; }
        public decimal TotalOverheads { get; set; }
        public decimal TotalCost { get; set; }
        public decimal TotalCostIncludingOverheads { get; set; }
        public decimal TotalMarkup { get; set; }
        public decimal TotalSalesValue { get; set; }
        public decimal AccountsSellingPrice { get; set; }
        public decimal CalculatedUnitCost { get; set; }
        public decimal SuggestedSellingPrice { get; set; }
        public decimal UnitProfit { get; set; }
        public decimal AverageMarkup { get; set; }
        public decimal TotalProfit { get; set; }
        public decimal AverageMarginPercentage { get; set; }
        public bool Phantom { get; set; }
        public string CostingFamilyGuid { get; set; }
        public bool TopLevelCostSession { get; set; }
        public long BomBuildPackageTypeID { get; set; }
        /// <summary>
        /// Required By ObjectStore
        /// </summary>
        public byte[] OpLock { get; set; }
        /// <summary>
        /// Required By ObjectStore
        /// </summary>
        public DateTime DateTimeCreated { get; set; }
        public string Comment { get; set; }
        public string CostingLog { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BomBuildPackage BomBuildPackage { get; set; }
        public virtual BomBuildPackageType BomBuildPackageType { get; set; }
        public virtual BomRecord BomRecord { get; set; }
        public virtual BomVersionStatus BomVersionStatus { get; set; }
        public virtual ICollection<BomCostSessionTotal> BomCostSessionTotals { get; set; }
        public virtual ICollection<BomCost> BomCosts { get; set; }
    }
}