// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class BomOperationComponent
    {
        public long BomOperationComponentID { get; set; }
        public long BomComponentLineID { get; set; }
        public long BomOperationLineID { get; set; }
        public decimal Quantity { get; set; }
        /// <summary>
        /// Required By ObjectStore
        /// </summary>
        public byte[] OpLock { get; set; }
        /// <summary>
        /// Required By ObjectStore
        /// </summary>
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BomComponentLine BomComponentLine { get; set; }
        public virtual BomOperationLine BomOperationLine { get; set; }
    }
}