// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class BomVersionsAttachedDocument
    {
        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public long? Locator { get; set; }

        public virtual BomVersionsHeader Header { get; set; }
    }
}