// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class CBAccount
    {
        public CBAccount()
        {
            CBAccountContacts = new HashSet<CBAccountContact>();
            CBAccountMemos = new HashSet<CBAccountMemo>();
            CBBankFeedTransactions = new HashSet<CBBankFeedTransaction>();
            CBBankLocations = new HashSet<CBBankLocation>();
            CBBankStatements = new HashSet<CBBankStatement>();
            CBCloudBankAccounts = new HashSet<CBCloudBankAccount>();
            CBDirectDebitTrans = new HashSet<CBDirectDebitTran>();
            CBDraftBankStatements = new HashSet<CBDraftBankStatement>();
            CBPaymentCloudProviderBanks = new HashSet<CBPaymentCloudProviderBank>();
            CBPendAccountTrans = new HashSet<CBPendAccountTran>();
            CBPostedAccountTrans = new HashSet<CBPostedAccountTran>();
            CBSettings = new HashSet<CBSetting>();
            CBShortTermCashProjectionAccounts = new HashSet<CBShortTermCashProjectionAccount>();
            NLSettings = new HashSet<NLSetting>();
            PLHistoricalSupplierTrans = new HashSet<PLHistoricalSupplierTran>();
            PLPendSupplierBatchTrans = new HashSet<PLPendSupplierBatchTran>();
            PLPendSupplierTrans = new HashSet<PLPendSupplierTran>();
            PLPostedSupplierTrans = new HashSet<PLPostedSupplierTran>();
            SLHistoricalCustomerTrans = new HashSet<SLHistoricalCustomerTran>();
            SLPendCustomerBatchTrans = new HashSet<SLPendCustomerBatchTran>();
            SLPostedCustomerTrans = new HashSet<SLPostedCustomerTran>();
            SOPInvoiceCreditArches = new HashSet<SOPInvoiceCreditArch>();
            SOPInvoiceCredits = new HashSet<SOPInvoiceCredit>();
            SOPOrderReturnArches = new HashSet<SOPOrderReturnArch>();
            SOPOrderReturns = new HashSet<SOPOrderReturn>();
            SOPPaymentMethods = new HashSet<SOPPaymentMethod>();
            SYSMerchantAccounts = new HashSet<SYSMerchantAccount>();
            TSHumanResources = new HashSet<TSHumanResource>();
        }

        public long CBAccountID { get; set; }
        public string AccountCode { get; set; }
        public string AccountDescription { get; set; }
        public string BankSortCode { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public long CBAccountTypeID { get; set; }
        public long AccountSYSCurrencyID { get; set; }
        public decimal CurrentBalanceInAccntCurrency { get; set; }
        public decimal CurrentBalanceInBaseCurrency { get; set; }
        public decimal OverdraftLimit { get; set; }
        public DateTime? LastStatementDate { get; set; }
        public decimal StatementBalance { get; set; }
        public string BankAccountHolderName { get; set; }
        public int LastStatementPageNumber { get; set; }
        public string BankAccountNominalNumber { get; set; }
        public string BankAccountNominalCostCentre { get; set; }
        public string BankAccountNominalDepartment { get; set; }
        public string BankChargesNominalNumber { get; set; }
        public string BankChargesNominalCostCentre { get; set; }
        public string BankChargesNominalDepartment { get; set; }
        public string ExchangeDiffNominalNumber { get; set; }
        public string ExchangeDiffNominalCostCentre { get; set; }
        public string ExchangeDiffNominalDepartment { get; set; }
        public string ElectronicBank { get; set; }
        public byte? ElectronicService { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public string IBANNumber { get; set; }
        public string BICNumber { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public long? CBBankFeedAccountID { get; set; }
        public bool IsBankCloudEnabled { get; set; }
        public DateTime? BankCloudDisabledDateTime { get; set; }
        public long SYSAccountStatusID { get; set; }
        public string StatusChangedBy { get; set; }
        public DateTime? StatusChangedDateTime { get; set; }

        public virtual SYSCurrency AccountSYSCurrency { get; set; }
        public virtual CBAccountType CBAccountType { get; set; }
        public virtual CBBankFeedAccount CBBankFeedAccount { get; set; }
        public virtual SYSAccountStatus SYSAccountStatus { get; set; }
        public virtual ICollection<CBAccountContact> CBAccountContacts { get; set; }
        public virtual ICollection<CBAccountMemo> CBAccountMemos { get; set; }
        public virtual ICollection<CBBankFeedTransaction> CBBankFeedTransactions { get; set; }
        public virtual ICollection<CBBankLocation> CBBankLocations { get; set; }
        public virtual ICollection<CBBankStatement> CBBankStatements { get; set; }
        public virtual ICollection<CBCloudBankAccount> CBCloudBankAccounts { get; set; }
        public virtual ICollection<CBDirectDebitTran> CBDirectDebitTrans { get; set; }
        public virtual ICollection<CBDraftBankStatement> CBDraftBankStatements { get; set; }
        public virtual ICollection<CBPaymentCloudProviderBank> CBPaymentCloudProviderBanks { get; set; }
        public virtual ICollection<CBPendAccountTran> CBPendAccountTrans { get; set; }
        public virtual ICollection<CBPostedAccountTran> CBPostedAccountTrans { get; set; }
        public virtual ICollection<CBSetting> CBSettings { get; set; }
        public virtual ICollection<CBShortTermCashProjectionAccount> CBShortTermCashProjectionAccounts { get; set; }
        public virtual ICollection<NLSetting> NLSettings { get; set; }
        public virtual ICollection<PLHistoricalSupplierTran> PLHistoricalSupplierTrans { get; set; }
        public virtual ICollection<PLPendSupplierBatchTran> PLPendSupplierBatchTrans { get; set; }
        public virtual ICollection<PLPendSupplierTran> PLPendSupplierTrans { get; set; }
        public virtual ICollection<PLPostedSupplierTran> PLPostedSupplierTrans { get; set; }
        public virtual ICollection<SLHistoricalCustomerTran> SLHistoricalCustomerTrans { get; set; }
        public virtual ICollection<SLPendCustomerBatchTran> SLPendCustomerBatchTrans { get; set; }
        public virtual ICollection<SLPostedCustomerTran> SLPostedCustomerTrans { get; set; }
        public virtual ICollection<SOPInvoiceCreditArch> SOPInvoiceCreditArches { get; set; }
        public virtual ICollection<SOPInvoiceCredit> SOPInvoiceCredits { get; set; }
        public virtual ICollection<SOPOrderReturnArch> SOPOrderReturnArches { get; set; }
        public virtual ICollection<SOPOrderReturn> SOPOrderReturns { get; set; }
        public virtual ICollection<SOPPaymentMethod> SOPPaymentMethods { get; set; }
        public virtual ICollection<SYSMerchantAccount> SYSMerchantAccounts { get; set; }
        public virtual ICollection<TSHumanResource> TSHumanResources { get; set; }
    }
}