// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class CBBankFeedAccountPosting
    {
        public CBBankFeedAccountPosting()
        {
            CBBankFeedPostingInstructions = new HashSet<CBBankFeedPostingInstruction>();
        }

        public long CBBankFeedAccountPostingID { get; set; }
        public long CBBankFeedTransactionID { get; set; }
        public string AccountantNarrative { get; set; }
        public decimal GrossAmount { get; set; }
        public decimal NetAmount { get; set; }
        public decimal TaxAmount { get; set; }

        public virtual CBBankFeedTransaction CBBankFeedTransaction { get; set; }
        public virtual ICollection<CBBankFeedPostingInstruction> CBBankFeedPostingInstructions { get; set; }
    }
}