// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class CBShortTermCashProjectionAccount
    {
        public long CBShortTermCashProjectionAccountID { get; set; }
        public long CBShortTermCashProjectionHeaderID { get; set; }
        public long CBAccountID { get; set; }
        public bool IncludeInForecast { get; set; }

        public virtual CBAccount CBAccount { get; set; }
        public virtual CBShortTermCashProjectionHeader CBShortTermCashProjectionHeader { get; set; }
    }
}