// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class CBShortTermCashProjectionDateType
    {
        public CBShortTermCashProjectionDateType()
        {
            CBShortTermCashProjectionHeaders = new HashSet<CBShortTermCashProjectionHeader>();
        }

        public long CBShortTermCashProjectionDateTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<CBShortTermCashProjectionHeader> CBShortTermCashProjectionHeaders { get; set; }
    }
}