// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class CBShortTermCashProjectionHeader
    {
        public CBShortTermCashProjectionHeader()
        {
            CBShortTermCashProjectionAccounts = new HashSet<CBShortTermCashProjectionAccount>();
            CBShortTermCashProjectionTrans = new HashSet<CBShortTermCashProjectionTran>();
        }

        public long CBShortTermCashProjectionHeaderID { get; set; }
        public long CBShortTermCashProjectionDateTypeID { get; set; }
        public DateTime DateFrom { get; set; }
        public DateTime DateTo { get; set; }
        public decimal BookBalanceForSelectedAccounts { get; set; }

        public virtual CBShortTermCashProjectionDateType CBShortTermCashProjectionDateType { get; set; }
        public virtual ICollection<CBShortTermCashProjectionAccount> CBShortTermCashProjectionAccounts { get; set; }
        public virtual ICollection<CBShortTermCashProjectionTran> CBShortTermCashProjectionTrans { get; set; }
    }
}