// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class EstOtherExpense
    {
        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public string TypeReference { get; set; }
        public string TypeDescription { get; set; }
        public string Notes { get; set; }
        public decimal Quantity { get; set; }
        public decimal CostPrice { get; set; }
        public decimal Total { get; set; }
        public long? EstID { get; set; }
        public string UnitOfSale { get; set; }

        public virtual EstStage Header { get; set; }
    }
}