// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class FAAssetTransactionType
    {
        public FAAssetTransactionType()
        {
            FADepreciationTrans = new HashSet<FADepreciationTran>();
        }

        public long FAAssetTransactionTypeID { get; set; }
        public string TransactionTypeName { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<FADepreciationTran> FADepreciationTrans { get; set; }
    }
}