// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class FADepreciationTran
    {
        public long FADepreciationTranID { get; set; }
        public long FAAssetID { get; set; }
        public DateTime TransactionDate { get; set; }
        public long FAAssetTransactionTypeID { get; set; }
        public decimal OldValue { get; set; }
        public decimal NewValue { get; set; }
        public decimal PostingValue { get; set; }
        public long? SYSAccountingPeriodID { get; set; }
        public long URN { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public string UserName { get; set; }
        public int UserNumber { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual FAAsset FAAsset { get; set; }
        public virtual FAAssetTransactionType FAAssetTransactionType { get; set; }
        public virtual SYSAccountingPeriod SYSAccountingPeriod { get; set; }
    }
}