// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class INCREASE_LinkedSalesOrdersCurrent
    {
        public string DestinationItem { get; set; }
        public DateTime? DocumentDate { get; set; }
        public string CustomerDocumentNo { get; set; }
    }
}