// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class INCREASE_vw_ForecastMonthlyBucketView
    {
        public long? ForecastID { get; set; }
        public long? ItemID { get; set; }
        public long? SLCustomerAccountID { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public string Monthname { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Adjustments { get; set; }
        public decimal? Actual { get; set; }
    }
}