// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class INCREASE_Code_Bin
    {
        public string Code { get; set; }
        public long BinItemID { get; set; }
    }
}