// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class INCREASE_BomMachineOp
    {
        public string BomReference { get; set; }
        public string Description { get; set; }
        public string ProcessReference { get; set; }
        public string ProcessDescription { get; set; }
        public double? RunTimeHours { get; set; }
        public string MachineReference { get; set; }
        public string MachineDescription { get; set; }
        public double? MachineHours { get; set; }
        public double? MachineMinutes { get; set; }
        public decimal MachineChargeRate { get; set; }
    }
}