// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class INCREASE_Bom_Cost1
    {
        public long BomRecordID { get; set; }
        public long BomCostSessionID { get; set; }
        public decimal QtyCosted { get; set; }
        public string CostHeadingName { get; set; }
        public decimal? TotalCost { get; set; }
        public string BomReference { get; set; }
        public string BomVersion { get; set; }
        public long BomVersionStatusID { get; set; }
    }
}