// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class INCREASE_Average_WO_Cost
    {
        public string BomReference { get; set; }
        public decimal? Materials { get; set; }
        public decimal? Labour { get; set; }
        public decimal? Machine { get; set; }
        public decimal? Subcontract { get; set; }
        public decimal? Tooling { get; set; }
        public decimal? Unit_Cost { get; set; }
        public int? Number_WOs { get; set; }
        public decimal? Sum_Qty { get; set; }
    }
}