// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class INCREASE_Location
    {
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
    }
}