// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class MachinesCalibrationHistory
    {
        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public DateTime? LastCalibration { get; set; }
        public string Result { get; set; }
        public DateTime? NextCalibration { get; set; }
        public string Repairs { get; set; }
        public string Notes { get; set; }

        public virtual Machine Header { get; set; }
    }
}