// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class NLBudgetApportPeriodPrcnt
    {
        public long NLBudgetApportPeriodPrcntID { get; set; }
        public long NLAnnualBudgetApportProfileID { get; set; }
        public long SYSAccountingPeriodID { get; set; }
        public decimal PercentageOfAnnualBudget { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual NLAnnualBudgetApportProfile NLAnnualBudgetApportProfile { get; set; }
        public virtual SYSAccountingPeriod SYSAccountingPeriod { get; set; }
    }
}