// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class Old200BOMAllocation
    {
        public Old200BOMAllocation()
        {
            BOMAllocComponents = new HashSet<BOMAllocComponent>();
            BOMAllocFinishedItems = new HashSet<BOMAllocFinishedItem>();
        }

        public long BOMAllocationID { get; set; }
        public string BOMAllocationName { get; set; }
        public long? WarehouseID { get; set; }
        public long BOMMakeupStockOptionID { get; set; }
        public long BOMMakeupSubAssOptionID { get; set; }
        public bool IsAllocationWithChanges { get; set; }
        public decimal TotalQtyForMake { get; set; }
        public bool IsClosed { get; set; }
        public DateTime AllocationDate { get; set; }
        public DateTime AllocationTime { get; set; }
        public string AllocatedBy { get; set; }
        public string UserAllocationReference { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BOMMakeupStockOption BOMMakeupStockOption { get; set; }
        public virtual BOMMakeupSubAssOption BOMMakeupSubAssOption { get; set; }
        public virtual ICollection<BOMAllocComponent> BOMAllocComponents { get; set; }
        public virtual ICollection<BOMAllocFinishedItem> BOMAllocFinishedItems { get; set; }
    }
}