// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class PayPortItemDiscVw
    {
        public long? CustomerDiscountGroupID { get; set; }
        public long? PriceBandID { get; set; }
        public long StkItmDiscID { get; set; }
        public string DiscGrpName { get; set; }
        public string PriceBandName { get; set; }
        public string ItemCode { get; set; }
        public long DiscountTypeID { get; set; }
        public long StockItemQtyDiscBreakID { get; set; }
        public decimal QuantityMoreThan { get; set; }
        public decimal DiscountAmountValue { get; set; }
        public decimal DiscountPercentValue { get; set; }
        public long StockItemDiscountID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
    }
}