// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class PCProjectArchiveUpdateVw
    {
        public long PCProjectItemID { get; set; }
        public long PCProjectArchiveStatusID { get; set; }
        public long PCTopLevelParentID { get; set; }
    }
}