// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class PCProjectLevel
    {
        public PCProjectLevel()
        {
            PCProjectLvlAnalFieldSettings = new HashSet<PCProjectLvlAnalFieldSetting>();
            PCProjectLvlFeatureSettings = new HashSet<PCProjectLvlFeatureSetting>();
        }

        public long PCProjectLevelID { get; set; }
        public string Title { get; set; }
        public long PCProjectLevelBillingMethodID { get; set; }
        public long PCProjectItemStatusID { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual PCProjectLevelBillingMethod PCProjectLevelBillingMethod { get; set; }
        public virtual ICollection<PCProjectLvlAnalFieldSetting> PCProjectLvlAnalFieldSettings { get; set; }
        public virtual ICollection<PCProjectLvlFeatureSetting> PCProjectLvlFeatureSettings { get; set; }
    }
}