// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class PCUnitOfMeasure
    {
        public PCUnitOfMeasure()
        {
            BLBillLines = new HashSet<BLBillLine>();
            BLContracts = new HashSet<BLContract>();
            PCAccruals = new HashSet<PCAccrual>();
            PCCostItemTypes = new HashSet<PCCostItemType>();
            PCCostItems = new HashSet<PCCostItem>();
            PCProjectEntries = new HashSet<PCProjectEntry>();
        }

        public long PCUnitOfMeasureID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<BLBillLine> BLBillLines { get; set; }
        public virtual ICollection<BLContract> BLContracts { get; set; }
        public virtual ICollection<PCAccrual> PCAccruals { get; set; }
        public virtual ICollection<PCCostItemType> PCCostItemTypes { get; set; }
        public virtual ICollection<PCCostItem> PCCostItems { get; set; }
        public virtual ICollection<PCProjectEntry> PCProjectEntries { get; set; }
    }
}