// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class POPRequisitionFulfilmentLineType
    {
        public POPRequisitionFulfilmentLineType()
        {
            POPRequisitionFulfilmentLines = new HashSet<POPRequisitionFulfilmentLine>();
        }

        public long POPRequisitionFulfilmentLineTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<POPRequisitionFulfilmentLine> POPRequisitionFulfilmentLines { get; set; }
    }
}