// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class POPRcptRtnInvCrdLineArch
    {
        public long POPRcptRtnInvCredLineID { get; set; }
        public long POPReceiptReturnLineID { get; set; }
        public long POPInvoiceCreditLineID { get; set; }
        public decimal InvoiceCreditQuantity { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public long IntrastatStatusID { get; set; }
        public decimal StockUnitInvCredQuantity { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual IntrastatStatus IntrastatStatus { get; set; }
        public virtual POPInvCreditLineArch POPInvoiceCreditLine { get; set; }
        public virtual POPRcptReturnLineArch POPReceiptReturnLine { get; set; }
    }
}