// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class POPSetting
    {
        public long POPSettingID { get; set; }
        public bool AutoGenOrderReturnNos { get; set; }
        public bool? ShowQtyGoodsReceived { get; set; }
        public bool AmendAnalysisCodes { get; set; }
        public bool AmendNominalCodes { get; set; }
        public bool? UserLogonAsOrderTaker { get; set; }
        public bool OrdersNeedAuthorisation { get; set; }
        public decimal AuthorisationThreshold { get; set; }
        public bool? StockNominalAcctSameAs { get; set; }
        public bool UseSameCCDeptAsSupplier { get; set; }
        public string VariancesNomAccountRef { get; set; }
        public string VariancesNomCostCentre { get; set; }
        public string VariancesNomDepartment { get; set; }
        public bool AnalysePostingsByCCDept { get; set; }
        public bool? MarkTextAsReceived { get; set; }
        public bool? MarkServLabAsReceived { get; set; }
        public bool? MatchInvCredToOrdRetOnly { get; set; }
        public bool UseDisputedInvoicing { get; set; }
        public bool AllowOtherSupplierTrans { get; set; }
        public bool RecordCancelledOrdLines { get; set; }
        public bool AutoPrintCopyOrders { get; set; }
        public bool GenerateIntrastatEntries { get; set; }
        public long? TermsOfDeliveryID { get; set; }
        public long? NatureOfTransCodeID { get; set; }
        public DateTime? OrderListLastUpdated { get; set; }
        public DateTime? OrdRtnsLastArchivedUpTo { get; set; }
        public string LastArchiveRunBy { get; set; }
        public DateTime? LastArchiveRunOn { get; set; }
        public bool UseCataloguePrice { get; set; }
        public string LastPurgeArchiveRunBy { get; set; }
        public DateTime? LastPurgeArchiveRunOn { get; set; }
        public DateTime? ArchiveLastPurgedUpTo { get; set; }
        public long? ModeOfTransportID { get; set; }
        public string LastProveBalancesRunBy { get; set; }
        public DateTime? LastProveBalancesRunOn { get; set; }
        public bool AllowManualDirectDelivery { get; set; }
        public bool AllowDirectDeliveryToCustomer { get; set; }
        public bool AllowDirectDeliveryToSupplier { get; set; }
        public bool AllowDirectDelToAnyAddress { get; set; }
        public long? PriceDifferenceNLAccountID { get; set; }
        public bool UpdatePriceOnGoodsReceipt { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public bool PricesSetAtGoodsReceipt { get; set; }
        public bool? UseOrderExchangeRateForPrices { get; set; }
        public long POPOrderGenerationTypeID { get; set; }
        public bool UseSinglePOForDirectDelivery { get; set; }
        public bool InclTermsOfDeliveryOnIntrastat { get; set; }
        public bool InclStatisticalValOnIntrastat { get; set; }
        public long IntrastatDateTypeID { get; set; }
        public bool InclTextInAccruals { get; set; }
        public bool InclServLabInAccruals { get; set; }
        public bool? IncludeBackToBackInOrderGeneration { get; set; }
        public bool ExcludeDirectDeliveryForCustomer { get; set; }
        public bool ExcludeViaStockForCustomer { get; set; }
        public bool ExcludeDirectDeliveryForOrder { get; set; }
        public bool ExcludeViaStockForOrder { get; set; }
        public long DefaultServLabConfirmIntent { get; set; }
        public long DefaultFreeTextConfirmIntent { get; set; }
        public bool? AllowUnauthorisedOrderProcessing { get; set; }
        public bool? AmendHeaderAnalysisCodes { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public bool? CommittedIncludesGoodsReceived { get; set; }
        public bool CheckBudgetsOnAuthorise { get; set; }
        public bool RequisitionMandatoryNominalCodes { get; set; }
        public bool RequisitionNominalsInBudget { get; set; }
        public bool RequisitionMandatorySupplier { get; set; }
        public bool RequisitionAuthoriserAmend { get; set; }

        public virtual ConfirmationIntentType DefaultFreeTextConfirmIntentNavigation { get; set; }
        public virtual ConfirmationIntentType DefaultServLabConfirmIntentNavigation { get; set; }
        public virtual IntrastatDateType IntrastatDateType { get; set; }
        public virtual ModeOfTransport ModeOfTransport { get; set; }
        public virtual NatureOfTransCode NatureOfTransCode { get; set; }
        public virtual POPOrderGenerationType POPOrderGenerationType { get; set; }
        public virtual NLNominalAccount PriceDifferenceNLAccount { get; set; }
        public virtual TermsOfDelivery TermsOfDelivery { get; set; }
    }
}