// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class PriceBookSetting
    {
        public long PriceBookSettingID { get; set; }
        public bool UseLimitedPriceBands { get; set; }
        public bool UseCustomerDiscountGroups { get; set; }
        public bool UseStockItemDiscounts { get; set; }
        public bool UseProductGroupDiscounts { get; set; }
        public bool UseQuantityBasedDiscounts { get; set; }
        public bool UseOrderValueDiscounts { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}