// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class PSExpressionLine
    {
        public long PSExpressionLineID { get; set; }
        public long PSSearchID { get; set; }
        public long PSLogicalOperatorDescriptorID { get; set; }
        public long PSCondOperatorDescriptorID { get; set; }
        public long PSFieldDescriptorID { get; set; }
        public string Value { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual PSCondOperatorDescriptor PSCondOperatorDescriptor { get; set; }
        public virtual PSFieldDescriptor PSFieldDescriptor { get; set; }
        public virtual PSLogicalOperatorDescriptor PSLogicalOperatorDescriptor { get; set; }
        public virtual PSSearch PSSearch { get; set; }
    }
}