// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class RTLDispatch
    {
        public long DispatchId { get; set; }
        public DateTime? DispatchDate { get; set; }
        public long HierNodeId { get; set; }
        public long StoreId { get; set; }
        public string DispatchUser { get; set; }
        public string DispatchRef { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}