// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class RTLPromoProduct
    {
        public long PromoPrdId { get; set; }
        public long PromoId { get; set; }
        public long PrdHierNodeId { get; set; }
        public string SageStockItemCode { get; set; }
        public int? ThresholdValue { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}