// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class RTLPricingDefaultsSupplier
    {
        public long PricingDefSuppsId { get; set; }
        public long PrdHierNodeId { get; set; }
        public string SupplierCode { get; set; }
        public bool IsPreferred { get; set; }
        public decimal? LastBuyingPrice { get; set; }
        public decimal? ListPrice { get; set; }
        public DateTime? DateListPriceChanged { get; set; }
        public DateTime? ListPriceExpiryDate { get; set; }
        public DateTime? DateTimeCreated { get; set; }
        public long DefaultPricingSourceTypeID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}