// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class RTLStockItemSupplier
    {
        public long SISId { get; set; }
        public long PrdHierNodeId { get; set; }
        public string SupplierCode { get; set; }
        public bool IsPreferred { get; set; }
        public int? LeadTime { get; set; }
        public string LeadTimeUnit { get; set; }
        public decimal? MinimumOrderQuantity { get; set; }
        public decimal? UsualOrderQuantity { get; set; }
        public decimal? OrderQuantityYtd { get; set; }
        public decimal? OrderValueYtd { get; set; }
        public decimal? QuantityOnOrder { get; set; }
        public string SupplierStockCode { get; set; }
        public long LandedCostsTypeID { get; set; }
        public decimal LandedCostsValue { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}