// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_DLP_DownloadReportUsageWOIssue
    {
        public long ItemID { get; set; }
        public decimal? Quantity { get; set; }
        public string TransactionGroupName { get; set; }
    }
}