// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class Sabre_DLP_VTG_Download_StockSum
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public decimal? Stock { get; set; }
    }
}