// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class Sabre_DLP_DownloadReport_KPI_TotalTransfersToInspection
    {
        public int? Total_Transfers_to_Inspection { get; set; }
    }
}