// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_DLP_DownloadReportStockList
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal StandardCost { get; set; }
        public DateTime? InactiveDate { get; set; }
        public string Manufacturer { get; set; }
        public string PartNumber { get; set; }
        public string CommodityCode { get; set; }
        public decimal AverageBuyingPrice { get; set; }
        public decimal FreeStock_All_ { get; set; }
        public decimal? FreeStock_Main_ { get; set; }
        public string DefaultDespatchNoteComment { get; set; }
        public string DefaultPickingListComment { get; set; }
        public string SpareText1 { get; set; }
        public string SpareText2 { get; set; }
        public string SpareText3 { get; set; }
        public decimal SpareNumber1 { get; set; }
        public decimal SpareNumber2 { get; set; }
        public decimal SpareNumber3 { get; set; }
        public DateTime? SpareDate1 { get; set; }
        public DateTime? SpareDate2 { get; set; }
        public DateTime? SpareDate3 { get; set; }
        public bool SpareBit1 { get; set; }
        public bool SpareBit2 { get; set; }
        public bool SpareBit3 { get; set; }
        public bool AllowSalesOrder { get; set; }
        public bool UsesSupplementaryUnit { get; set; }
        public decimal SupplementaryUnitConversionRatio { get; set; }
        public string Description { get; set; }
        public string ProductGroup { get; set; }
        public bool DoItemsUseUnits { get; set; }
        public bool SellQuantsUseMultUnits { get; set; }
        public bool BuyQuantsUseMultUnits { get; set; }
        public bool SellPricesUseMultUnits { get; set; }
        public bool BuyPricesUseMultUnits { get; set; }
        public string StockItemStatusName { get; set; }
        public string TraceableType { get; set; }
        public string LandedCostsType { get; set; }
        public string StockItemDiscount { get; set; }
        public string BOMItemType { get; set; }
        public string SOPOrderFulfilmentMethodName { get; set; }
        public string STKShelfLifeType { get; set; }
        public string STKFulfilmentSequenceType { get; set; }
        public int? AggregateDays { get; set; }
        public decimal? WorksOrderBatchMinQty { get; set; }
        public decimal? WorksOrderBatchMaxQty { get; set; }
        public bool? CanCancelWorksOrders { get; set; }
        public bool? CanCancelPurchaseOrders { get; set; }
        public decimal? MRPReplenishmentMultipleValue { get; set; }
        public bool? CanAmendPOReceiptAllocation { get; set; }
        public bool? Linked { get; set; }
        public bool? UseDemandWarehouse { get; set; }
        public bool? UseWOCompletionWarehouse { get; set; }
        public short? ReplenishmentHorizonDays { get; set; }
        public bool? ApplyReorderLevelAfterMaximum { get; set; }
        public bool? BuiltBoughtDefaultMake { get; set; }
        public string Warehouse { get; set; }
        public decimal? ReorderLevel { get; set; }
        public decimal? MinimumLevel { get; set; }
        public decimal? MaximumLevel { get; set; }
        public DateTime? DateOfLastSale { get; set; }
        public decimal? ConfirmedQtyInStock { get; set; }
        public decimal? UnconfirmedQtyInStock { get; set; }
        public decimal? QuantityAllocatedSOP { get; set; }
        public decimal? QuantityAllocatedStock { get; set; }
        public decimal? QuantityOnPOPOrder { get; set; }
        public decimal? HoldingValueAtBuyPrice { get; set; }
        public decimal? PreReceiptAllocationQty { get; set; }
        public decimal? QuantityAllocatedBOM { get; set; }
        public decimal? TotalQuantityIssued { get; set; }
        public decimal? QuantityReceived { get; set; }
        public decimal? WOIssue { get; set; }
        public decimal? StoresIssue1Week { get; set; }
        public bool? PreferredSupplier { get; set; }
        public short? LeadTime { get; set; }
        public string SupplierAccountName { get; set; }
        public decimal? Quantity { get; set; }
        public int? TotalBOMApperances { get; set; }
        public DateTime? Last_Received_Date { get; set; }
        public DateTime? Last_Issued_Date { get; set; }
    }
}