// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_DLP_Koni070
    {
        public string CatNo { get; set; }
        public string Unit { get; set; }
        public string OperationCode { get; set; }
        public byte Minutes { get; set; }
        public string BomVersionStatus { get; set; }
        public string Description { get; set; }
    }
}