// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class Sabre_DLP_SLDespatchRole
    {
        public string CustomerAccountNumber { get; set; }
        public string CustomerAccountName { get; set; }
        public string ContactName { get; set; }
        public string ContactValue { get; set; }
        public string Role { get; set; }
        public bool? IsPreferredValue { get; set; }
        public long? SYSContactTypeID { get; set; }
    }
}