// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_DLP_BOM_WHEREUSE
    {
        public string BomReference { get; set; }
        public string Description { get; set; }
        public string StockCode { get; set; }
        public string Item { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public short VersionStatus { get; set; }
        public string Revision { get; set; }
    }
}