// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_BC_Operation
    {
        public string Next_Op_Code { get; set; }
        public string Next_Operation { get; set; }
    }
}