// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_DLP_SlowMovingStock_2
    {
        public string Stock_Code { get; set; }
        public string Description { get; set; }
        public string Product_Group { get; set; }
        public string Location { get; set; }
        public decimal? Last_Cost { get; set; }
        public decimal Last_Invoice_Price { get; set; }
        public string Issue_Type { get; set; }
        public decimal? Stock { get; set; }
        public decimal? Allocated { get; set; }
        public decimal? TheoStock { get; set; }
        public decimal? Usage_1_Month { get; set; }
        public decimal? Usage_12_Months { get; set; }
        public decimal? Usage_24_Month { get; set; }
    }
}