// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_DLP_Max_TransactionHistory
    {
        public long ItemID { get; set; }
        public DateTime? Trans_date { get; set; }
    }
}