// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_DLP_SUPPLIER_LINE
    {
        public string Lines_Rasied_On { get; set; }
        public int? Total_Lines_Raised { get; set; }
    }
}