// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRERAIL_DLP_KPI_GoodsIn
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string ProductGroup { get; set; }
        public string TransactionGroupName { get; set; }
        public DateTime TransactionDate { get; set; }
        public decimal Quantity { get; set; }
        public string MovementBalanceTypeName { get; set; }
        public string TransactionTypeName { get; set; }
        public string SecondReference { get; set; }
    }
}