// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SABRE_RAIL_DLP_SalesForecastDespatch_Month
    {
        public string Cust_Acc { get; set; }
        public string Cust_Name { get; set; }
        public int? Year { get; set; }
        public int? Month { get; set; }
        public decimal? DespatchQty { get; set; }
        public string Stock_Code { get; set; }
        public string Stock_Description { get; set; }
    }
}