// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class salesforecastdetails_sabre
    {
        public int sfdId { get; set; }
        public long sfdHeaderID { get; set; }
        public string sfdProductCode { get; set; }
        public string sfdCustomerCode { get; set; }
        public int sfdQty { get; set; }
        public DateTime sfdDate { get; set; }
        public string sfdDescription { get; set; }
    }
}