// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SLCustomerContactValue
    {
        public SLCustomerContactValue()
        {
            SLCustomerDocuments = new HashSet<SLCustomerDocument>();
        }

        public long SLCustomerContactValueID { get; set; }
        public long SLCustomerContactID { get; set; }
        public long SYSContactTypeID { get; set; }
        public string ContactValue { get; set; }
        public bool IsPreferredValue { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public string ContactValueCountryCode { get; set; }
        public string ContactValueAreaCode { get; set; }
        public string ContactValueSubscriberNumber { get; set; }
        public string ContactValuePreMigratedData { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SLCustomerContact SLCustomerContact { get; set; }
        public virtual SYSContactType SYSContactType { get; set; }
        public virtual ICollection<SLCustomerDocument> SLCustomerDocuments { get; set; }
    }
}