// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SLHistoricalCustomerTran
    {
        public SLHistoricalCustomerTran()
        {
            CBGroupHistCustomerTrans = new HashSet<CBGroupHistCustomerTran>();
            SLHistRevalAllocationTrans = new HashSet<SLHistRevalAllocationTran>();
        }

        public long SLHistoricalCustomerTranID { get; set; }
        public long SLCustomerAccountID { get; set; }
        public long SYSTraderTranTypeID { get; set; }
        public long? CBAccountID { get; set; }
        public DateTime TransactionDate { get; set; }
        public string TransactionReference { get; set; }
        public string SecondReference { get; set; }
        public decimal GoodsValueInAccountCurrency { get; set; }
        public decimal SalControlValueInBaseCurrency { get; set; }
        public decimal TaxValue { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal DiscountPercentage { get; set; }
        public short DaysDiscountValid { get; set; }
        public decimal AllocatedValue { get; set; }
        public DateTime DueDate { get; set; }
        public decimal DocumentToBaseCurrencyRate { get; set; }
        public decimal DocumentToAccountExchangeRate { get; set; }
        public DateTime PostedDate { get; set; }
        public string QueryCode { get; set; }
        public long Source { get; set; }
        public long UniqueReferenceNumber { get; set; }
        public string UserName { get; set; }
        public int UserNumber { get; set; }
        public DateTime DateTransactionMovedToHistory { get; set; }
        public DateTime? FullSettlementDate { get; set; }
        public short FullSettlementPeriodInDays { get; set; }
        public long SYSTraderGenerateReasonTypeID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public bool Revalued { get; set; }
        public decimal EffectiveExchangeRate { get; set; }
        public long? NominalAccountingPeriodID { get; set; }
        public bool TriangularTransaction { get; set; }
        public decimal ESVatDiscountAmount { get; set; }
        public bool IsSettledImmediately { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public long SYSCorrectionTranTypeID { get; set; }
        public string PaymentCloudPaymentID { get; set; }

        public virtual CBAccount CBAccount { get; set; }
        public virtual SYSAccountingPeriod NominalAccountingPeriod { get; set; }
        public virtual SLCustomerAccount SLCustomerAccount { get; set; }
        public virtual SYSCorrectionTranType SYSCorrectionTranType { get; set; }
        public virtual SYSTraderGenerateReasonType SYSTraderGenerateReasonType { get; set; }
        public virtual SYSTraderTranType SYSTraderTranType { get; set; }
        public virtual ICollection<CBGroupHistCustomerTran> CBGroupHistCustomerTrans { get; set; }
        public virtual ICollection<SLHistRevalAllocationTran> SLHistRevalAllocationTrans { get; set; }
    }
}