// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SOPAdditionalChargeView
    {
        public string mmssac_Code { get; set; }
        public string mmssac_ChargeName { get; set; }
        public string mmssac_TaxName { get; set; }
        public string mmssac_LineTotalValue { get; set; }
        public string mmssac_LineTaxValue { get; set; }
        public long mmssac_SOPOrderReturnID { get; set; }
    }
}