// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SOPOrdersView
    {
        public long mmssoos_DocumentTypeID { get; set; }
        public string mmssoos_OrderDocumentNo { get; set; }
        public DateTime? mmssoos_DocumentDate { get; set; }
        public DateTime? mmssoos_PromisedDeliveryDate { get; set; }
        public string mmssoos_DocumentCreatedBy { get; set; }
        public DateTime? mmssoos_RequestedDeliveryDate { get; set; }
        public double? mmssoos_TotalNetValue { get; set; }
        public double? mmssoos_TotalTaxValue { get; set; }
        public double? mmssoos_TotalGrossValue { get; set; }
        public double? mmssoos_TotalGrossValueIncSett { get; set; }
        public string mmssoos_Status { get; set; }
        public string mmssoos_CustomerDocumentNo { get; set; }
        public string mmssoos_SourceDocumentNo { get; set; }
        public string mmssoos_CustomerAccountNumber { get; set; }
        public long mmssoos_SOPOrderReturnID { get; set; }
        public long mmssoos_SLCustomerAccountID { get; set; }
        public string mmssoos_ExternalReference { get; set; }
    }
}