// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SOPOrderFulfilmentMethod
    {
        public SOPOrderFulfilmentMethod()
        {
            SOPOrderReturnLineArches = new HashSet<SOPOrderReturnLineArch>();
            SOPOrderReturnLines = new HashSet<SOPOrderReturnLine>();
            StockItems = new HashSet<StockItem>();
        }

        public long SOPOrderFulfilmentMethodID { get; set; }
        public string SOPOrderFulfilmentMethodName { get; set; }

        public virtual ICollection<SOPOrderReturnLineArch> SOPOrderReturnLineArches { get; set; }
        public virtual ICollection<SOPOrderReturnLine> SOPOrderReturnLines { get; set; }
        public virtual ICollection<StockItem> StockItems { get; set; }
    }
}