// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SOPOrderLinesDespatchView
    {
        public string mmssold_ItemCode { get; set; }
        public string mmssold_OrderDocumentNumber { get; set; }
        public string mmssold_DespatchReceiptNo { get; set; }
        public DateTime mmssold_DespatchReceiptDate { get; set; }
        public string mmssold_DespatchedBy { get; set; }
        public double? mmssold_DespatchReceiptQuantity { get; set; }
        public long mmssold_CustomerID { get; set; }
        public long mmssold_SOPOrderReturnID { get; set; }
    }
}