// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SOPPreferredItem
    {
        public long SOPPreferredItemID { get; set; }
        public long SLCustomerAccountID { get; set; }
        public long? ItemID { get; set; }
        public long LineTypeID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual StockItem Item { get; set; }
        public virtual OrderReturnLineType LineType { get; set; }
        public virtual SLCustomerAccount SLCustomerAccount { get; set; }
    }
}