// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SOPUser
    {
        public SOPUser()
        {
            UserDefaultWarehouses = new HashSet<UserDefaultWarehouse>();
        }

        public long SOPUserID { get; set; }
        public int UserNumber { get; set; }

        public virtual SOPUserPermission SOPUserPermission { get; set; }
        public virtual ICollection<UserDefaultWarehouse> UserDefaultWarehouses { get; set; }
    }
}