// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class STKAutoGenerateSeparator
    {
        public STKAutoGenerateSeparator()
        {
            StockItems = new HashSet<StockItem>();
        }

        public long STKAutoGenerateSeparatorID { get; set; }
        public string Name { get; set; }
        public string SeparatorCharacter { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<StockItem> StockItems { get; set; }
    }
}