// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class STKStockTakeItemView
    {
        public DateTime? BIDateOfLastStockCount { get; set; }
        public DateTime? WIDateOfLastStockCount { get; set; }
        public long StocktakeID { get; set; }
        public bool ActualQuantityEntered { get; set; }
        public long TraceableTypeID { get; set; }
    }
}