// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class StockItemX
    {
        public long StockItemXID { get; set; }
        public string IssueMethod { get; set; }
        public string ProductClassification { get; set; }
        public bool MadeInHouse { get; set; }
        public string CommodityCode2 { get; set; }
        public bool Short { get; set; }
        public string ShortComments { get; set; }
        public int KanbanSNP { get; set; }
        public string KanbanLocation { get; set; }
        public bool FitForPurpose { get; set; }
        public bool AtInspection { get; set; }
        public bool EngineeringSample { get; set; }
        public DateTime? ProductionStartDate { get; set; }
        public int MultipleOrderQuantity { get; set; }
        public DateTime? ReleasedFromInspection { get; set; }
        public bool InspectionRequired { get; set; }
        public bool ISIRRequired { get; set; }
        public bool CofCRequired { get; set; }
        public bool MSDSRequired { get; set; }
        public bool MSDSApproved { get; set; }
        public string MSDSApprovedBy { get; set; }
        public DateTime? MSDSApprovedDate { get; set; }
        public bool RiskAssessmentReqd { get; set; }
        public int MinimumSellQuantity { get; set; }
        public int MultiplesOffSellQty { get; set; }
        public string SalesOrderType { get; set; }
        public bool NonMandatory { get; set; }
        public string SabreSpareText1 { get; set; }
        public string SabreSpareText2 { get; set; }
        public string SabreSpareText3 { get; set; }
        public string SabreSpareText4 { get; set; }
        public string SabreSpareText5 { get; set; }
        public decimal SabreSpareNumber1 { get; set; }
        public decimal SabreSpareNumber2 { get; set; }
        public decimal SabreSpareNumber3 { get; set; }
        public decimal SabreSpareNumber4 { get; set; }
        public decimal SabreSpareNumber5 { get; set; }
        public DateTime? SabreSpareDate1 { get; set; }
        public DateTime? SabreSpareDate2 { get; set; }
        public DateTime? SabreSpareDate3 { get; set; }
        public DateTime? SabreSpareDate4 { get; set; }
        public DateTime? SabreSpareDate5 { get; set; }
        public bool SabreSpareBit1 { get; set; }
        public bool SabreSpareBit2 { get; set; }
        public bool SabreSpareBit3 { get; set; }
        public bool SabreSpareBit4 { get; set; }
        public bool SabreSpareBit5 { get; set; }

        public virtual StockItem StockItemXNavigation { get; set; }
    }
}