// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class StockItemUnit
    {
        public StockItemUnit()
        {
            POPStandardItemLinkArchBuyingPriceUnits = new HashSet<POPStandardItemLinkArch>();
            POPStandardItemLinkArchBuyingUnits = new HashSet<POPStandardItemLinkArch>();
            POPStandardItemLinkBuyingPriceUnits = new HashSet<POPStandardItemLink>();
            POPStandardItemLinkBuyingUnits = new HashSet<POPStandardItemLink>();
            SOPStandardItemLinkArchSellingPriceUnits = new HashSet<SOPStandardItemLinkArch>();
            SOPStandardItemLinkArchSellingUnits = new HashSet<SOPStandardItemLinkArch>();
            SOPStandardItemLinkSellingPriceUnits = new HashSet<SOPStandardItemLink>();
            SOPStandardItemLinkSellingUnits = new HashSet<SOPStandardItemLink>();
            StockItemDiscounts = new HashSet<StockItemDiscount>();
            StockItemUnitUOMTypes = new HashSet<StockItemUnitUOMType>();
            TEMItemUnitMappings = new HashSet<TEMItemUnitMapping>();
        }

        public long StockItemUnitID { get; set; }
        public long ItemID { get; set; }
        public long UnitID { get; set; }
        public decimal MultipleOfBaseUnit { get; set; }
        public bool UseOwnPrice { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public decimal UnitPrecision { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual StockItem Item { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<POPStandardItemLinkArch> POPStandardItemLinkArchBuyingPriceUnits { get; set; }
        public virtual ICollection<POPStandardItemLinkArch> POPStandardItemLinkArchBuyingUnits { get; set; }
        public virtual ICollection<POPStandardItemLink> POPStandardItemLinkBuyingPriceUnits { get; set; }
        public virtual ICollection<POPStandardItemLink> POPStandardItemLinkBuyingUnits { get; set; }
        public virtual ICollection<SOPStandardItemLinkArch> SOPStandardItemLinkArchSellingPriceUnits { get; set; }
        public virtual ICollection<SOPStandardItemLinkArch> SOPStandardItemLinkArchSellingUnits { get; set; }
        public virtual ICollection<SOPStandardItemLink> SOPStandardItemLinkSellingPriceUnits { get; set; }
        public virtual ICollection<SOPStandardItemLink> SOPStandardItemLinkSellingUnits { get; set; }
        public virtual ICollection<StockItemDiscount> StockItemDiscounts { get; set; }
        public virtual ICollection<StockItemUnitUOMType> StockItemUnitUOMTypes { get; set; }
        public virtual ICollection<TEMItemUnitMapping> TEMItemUnitMappings { get; set; }
    }
}