// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class STPricesForStockItemView
    {
        public string mmsstp_PriceBandName { get; set; }
        public string mmsstp_Description { get; set; }
        public long? mmsstp_PriceBandID { get; set; }
        public decimal mmsstp_Price { get; set; }
        public long mmsstp_ItemID { get; set; }
        public string mmsstp_CurrencyName { get; set; }
        public string mmsstp_CustomerAccountNumber { get; set; }
        public long? mmsstp_CustomersPriceBandID { get; set; }
    }
}