// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SubContractingPurchaseOrder
    {
        public long ID { get; set; }
        public string Source { get; set; }
        public long OpID { get; set; }
        public string POrderNumber { get; set; }
        public string SupplierRef { get; set; }
        public long ItemNumber { get; set; }
        public decimal Quantity { get; set; }
    }
}