// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSActiveLock
    {
        public long SYSActiveLockID { get; set; }
        public long SYSUserLoginID { get; set; }
        public string OptionName { get; set; }
        public string Data { get; set; }
        public string UserName { get; set; }
        public string Workstation { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? TimeCreated { get; set; }
        public long? ProcessID { get; set; }
        public long? DataKey { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSUserLogin SYSUserLogin { get; set; }
    }
}