// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSAuditLogDetail
    {
        public long SYSAuditLogDetailID { get; set; }
        public long SYSAuditLogHeaderID { get; set; }
        public string FieldName { get; set; }
        public string FriendlyName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSAuditLogHeader SYSAuditLogHeader { get; set; }
    }
}