// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSCorrectionTranType
    {
        public SYSCorrectionTranType()
        {
            CBPostedAccountTrans = new HashSet<CBPostedAccountTran>();
            NLDeferredNominalTrans = new HashSet<NLDeferredNominalTran>();
            NLHistoricalNominalTrans = new HashSet<NLHistoricalNominalTran>();
            NLPendNominalTrans = new HashSet<NLPendNominalTran>();
            NLPostedNominalTrans = new HashSet<NLPostedNominalTran>();
            PLHistoricalSupplierTrans = new HashSet<PLHistoricalSupplierTran>();
            PLPostedSupplierTrans = new HashSet<PLPostedSupplierTran>();
            SLHistoricalCustomerTrans = new HashSet<SLHistoricalCustomerTran>();
            SLPostedCustomerTrans = new HashSet<SLPostedCustomerTran>();
        }

        public long SYSCorrectionTranTypeID { get; set; }
        public string Name { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<CBPostedAccountTran> CBPostedAccountTrans { get; set; }
        public virtual ICollection<NLDeferredNominalTran> NLDeferredNominalTrans { get; set; }
        public virtual ICollection<NLHistoricalNominalTran> NLHistoricalNominalTrans { get; set; }
        public virtual ICollection<NLPendNominalTran> NLPendNominalTrans { get; set; }
        public virtual ICollection<NLPostedNominalTran> NLPostedNominalTrans { get; set; }
        public virtual ICollection<PLHistoricalSupplierTran> PLHistoricalSupplierTrans { get; set; }
        public virtual ICollection<PLPostedSupplierTran> PLPostedSupplierTrans { get; set; }
        public virtual ICollection<SLHistoricalCustomerTran> SLHistoricalCustomerTrans { get; set; }
        public virtual ICollection<SLPostedCustomerTran> SLPostedCustomerTrans { get; set; }
    }
}