// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSDesktopListFilter
    {
        public long SYSDesktopListFilterID { get; set; }
        public string DesktopList { get; set; }
        public string FilterName { get; set; }
        public long? UserID { get; set; }
        public string SerializedFilter { get; set; }
    }
}