// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSDocTransmissionMethod
    {
        public SYSDocTransmissionMethod()
        {
            PLSupplierDocuments = new HashSet<PLSupplierDocument>();
            SLCustomerDocuments = new HashSet<SLCustomerDocument>();
        }

        public long SYSDocTransmissionMethodID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PLSupplierDocument> PLSupplierDocuments { get; set; }
        public virtual ICollection<SLCustomerDocument> SLCustomerDocuments { get; set; }
    }
}