// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSDocStorageSetting
    {
        public long SYSDocStorageSettingID { get; set; }
        public string LocalFolderPath { get; set; }
        public string CloudFolderPath { get; set; }
        public bool PrintingEnabled { get; set; }
        public bool EmailEnabled { get; set; }
        public bool ConfirmSave { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}