// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSReportKey
    {
        public long SYSReportKeyID { get; set; }
        public string ReportName { get; set; }
        public string ReportFileName { get; set; }
        public bool UploadToDocumentStorage { get; set; }
    }
}