// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSTranDateValidationType
    {
        public SYSTranDateValidationType()
        {
            SYSTranDateValidationTerms = new HashSet<SYSTranDateValidationTerm>();
        }

        public long SYSTranDateValidationTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SYSTranDateValidationTerm> SYSTranDateValidationTerms { get; set; }
    }
}