// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSTraderContactRole
    {
        public SYSTraderContactRole()
        {
            PLSupplierContactRoles = new HashSet<PLSupplierContactRole>();
            SLCustomerContactRoles = new HashSet<SLCustomerContactRole>();
            SYSDocumentTypes = new HashSet<SYSDocumentType>();
        }

        public long SYSTraderContactRoleID { get; set; }
        public string Role { get; set; }
        public bool IsDefaultRole { get; set; }
        public bool? UseForCustomerAccounts { get; set; }
        public bool? UseForSupplierAccounts { get; set; }
        public bool IsMandatory { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public bool UseWithDocuments { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<PLSupplierContactRole> PLSupplierContactRoles { get; set; }
        public virtual ICollection<SLCustomerContactRole> SLCustomerContactRoles { get; set; }
        public virtual ICollection<SYSDocumentType> SYSDocumentTypes { get; set; }
    }
}