// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSTaxTran
    {
        public long SYSTaxTranID { get; set; }
        public string AccountNumber { get; set; }
        public string CostCentre { get; set; }
        public string Department { get; set; }
        public decimal GoodsAmount { get; set; }
        public string Reference { get; set; }
        public long Source { get; set; }
        public DateTime TaxPointDate { get; set; }
        public DateTime PostedDate { get; set; }
        public long SYSTaxTranTypeID { get; set; }
        public long UniqueReferenceNumber { get; set; }
        public int UserNumber { get; set; }
        public decimal VatAmount { get; set; }
        public DateTime? VatReturnDate { get; set; }
        public long SYSTaxRateID { get; set; }
        public long SYSTaxPeriodRateBalanceID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public long? NominalAccountingPeriodID { get; set; }
        public bool TriangularTransaction { get; set; }
        public decimal ESVatDiscountAmount { get; set; }
        public bool IsSettledImmediately { get; set; }
        public bool IsVATAdjustmentDocumentExpected { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public string TaxAnalysisDetails { get; set; }
        public string TaxRegistrationNumber { get; set; }

        public virtual SYSAccountingPeriod NominalAccountingPeriod { get; set; }
        public virtual SYSTaxPeriodRateBalance SYSTaxPeriodRateBalance { get; set; }
        public virtual SYSTaxRate SYSTaxRate { get; set; }
        public virtual SYSTaxTranType SYSTaxTranType { get; set; }
    }
}