// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class SYSTraderGenerateReasonType
    {
        public SYSTraderGenerateReasonType()
        {
            PLHistoricalSupplierTrans = new HashSet<PLHistoricalSupplierTran>();
            PLPendSupplierTrans = new HashSet<PLPendSupplierTran>();
            SLHistoricalCustomerTrans = new HashSet<SLHistoricalCustomerTran>();
            SLPostedCustomerTrans = new HashSet<SLPostedCustomerTran>();
        }

        public long SYSTraderGenerateReasonTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PLHistoricalSupplierTran> PLHistoricalSupplierTrans { get; set; }
        public virtual ICollection<PLPendSupplierTran> PLPendSupplierTrans { get; set; }
        public virtual ICollection<SLHistoricalCustomerTran> SLHistoricalCustomerTrans { get; set; }
        public virtual ICollection<SLPostedCustomerTran> SLPostedCustomerTrans { get; set; }
    }
}