// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class TEMSupplierMapping
    {
        public long TEMSupplierMappingID { get; set; }
        public long SupplierID { get; set; }
        public string Name { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public string OriginatorsCode { get; set; }
        public long? DefaultNominalCodeID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual PLSupplierAccount Supplier { get; set; }
    }
}