// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class TermsOfDelivery
    {
        public TermsOfDelivery()
        {
            IntrastatEntries = new HashSet<IntrastatEntry>();
            POPSettings = new HashSet<POPSetting>();
            SOPSettings = new HashSet<SOPSetting>();
        }

        public long TermsOfDeliveryID { get; set; }
        public string Code { get; set; }
        public long? CountryCodeID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSCountryCode CountryCode { get; set; }
        public virtual ICollection<IntrastatEntry> IntrastatEntries { get; set; }
        public virtual ICollection<POPSetting> POPSettings { get; set; }
        public virtual ICollection<SOPSetting> SOPSettings { get; set; }
    }
}