// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class TraceSOPDespRcptLine
    {
        public long TraceSOPDespRcptLineID { get; set; }
        public long SOPDespatchReceiptLineID { get; set; }
        public long TraceableBinItemID { get; set; }
        public decimal Quantity { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SOPDespatchReceiptLine SOPDespatchReceiptLine { get; set; }
        public virtual TraceableBinItem TraceableBinItem { get; set; }
    }
}