// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class TSAuthorisationGroup
    {
        public TSAuthorisationGroup()
        {
            TSAuthGroupAuthorisers = new HashSet<TSAuthGroupAuthoriser>();
            TSAuthGroupMembers = new HashSet<TSAuthGroupMember>();
        }

        public long TSAuthorisationGroupID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<TSAuthGroupAuthoriser> TSAuthGroupAuthorisers { get; set; }
        public virtual ICollection<TSAuthGroupMember> TSAuthGroupMembers { get; set; }
    }
}