// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class TSPaymentFrequencyType
    {
        public TSPaymentFrequencyType()
        {
            TSHumanResources = new HashSet<TSHumanResource>();
        }

        public long TSPaymentFrequencyTypeID { get; set; }
        public string Description { get; set; }

        public virtual ICollection<TSHumanResource> TSHumanResources { get; set; }
    }
}