// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class TSPayRate
    {
        public TSPayRate()
        {
            TSHumanResourcePayRateLinks = new HashSet<TSHumanResourcePayRateLink>();
            TSTimeRecords = new HashSet<TSTimeRecord>();
        }

        public long TSPayRateID { get; set; }
        public string Description { get; set; }
        public decimal PayRateValue { get; set; }
        public bool IsDefault { get; set; }
        public bool IsAssignable { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public long TSPayRateTypeID { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual TSPayRateType TSPayRateType { get; set; }
        public virtual ICollection<TSHumanResourcePayRateLink> TSHumanResourcePayRateLinks { get; set; }
        public virtual ICollection<TSTimeRecord> TSTimeRecords { get; set; }
    }
}