// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class TSPostingMethodType
    {
        public TSPostingMethodType()
        {
            TSTimeFinancialsIntegrations = new HashSet<TSTimeFinancialsIntegration>();
        }

        public long TSPostingMethodID { get; set; }
        public string Description { get; set; }

        public virtual ICollection<TSTimeFinancialsIntegration> TSTimeFinancialsIntegrations { get; set; }
    }
}