// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class Unit
    {
        public Unit()
        {
            ProductGroupUnits = new HashSet<ProductGroupUnit>();
            StockItemUnits = new HashSet<StockItemUnit>();
        }

        public long UnitID { get; set; }
        public string Name { get; set; }
        public decimal MultipleOfBaseUnit { get; set; }
        public bool EachValue { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<ProductGroupUnit> ProductGroupUnits { get; set; }
        public virtual ICollection<StockItemUnit> StockItemUnits { get; set; }
    }
}