// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class vw_MrpRecommendationsWithNeededByDate
    {
        public long PlanMrpRecommendationID { get; set; }
        public string RecNumber { get; set; }
        public string Action { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public long BomHeaderID { get; set; }
        public string BuyerCode { get; set; }
        public string BuyerCodeFirstName { get; set; }
        public string BuyerCodeLastName { get; set; }
        public string BuyerCodeMiddleName { get; set; }
        public long BuyerCodeSalutationID { get; set; }
        public decimal CostPrice { get; set; }
        public string CreatedReference { get; set; }
        public string DelAddressName { get; set; }
        public string DelAddressLine1 { get; set; }
        public string DelAddressLine2 { get; set; }
        public string DelAddressLine3 { get; set; }
        public string DelAddressLine4 { get; set; }
        public string DelAddressPostcode { get; set; }
        public string DelAddressCity { get; set; }
        public string DelAddressCounty { get; set; }
        public long? DelAddressCountryID { get; set; }
        public string DelAddressCountry { get; set; }
        public string Description { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? DueLessSafety { get; set; }
        public DateTime? EndDate { get; set; }
        public short LeadTime { get; set; }
        public bool IsExcludedFromPlanner { get; set; }
        public bool IsExcludedFromStockProjection { get; set; }
        public bool FlaggedForFollowUp { get; set; }
        public bool IsLinked { get; set; }
        public long OperationDBKey { get; set; }
        public string OperationSourceModule { get; set; }
        public string OrderDetails { get; set; }
        public long POPOrderReturnLineID { get; set; }
        public int Priority { get; set; }
        public string ParentTag { get; set; }
        public string StockCode { get; set; }
        public decimal ActualQuantity { get; set; }
        public decimal AdjustedQuantity { get; set; }
        public long SplitID { get; set; }
        public long EstimateStageID { get; set; }
        public DateTime? StartDate { get; set; }
        public string Status { get; set; }
        public bool IsSubcontract { get; set; }
        public string SupplierAccountNumber { get; set; }
        public long? WarehouseID { get; set; }
        public long WorksOrderID { get; set; }
        public string WarehouseName { get; set; }
        public string CreatedFromRecommendation { get; set; }
        public string BuyerCodeKey { get; set; }
        public string SupplierKey { get; set; }
        public string ProductGroupCode { get; set; }
        public string ProductGroupName { get; set; }
        public string PlanPeriod { get; set; }
        public DateTime? NeededByDate { get; set; }
        public bool? IsLate { get; set; }
        public string UnitOfMeasure { get; set; }
    }
}