// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class vw_RepSupplier
    {
        public long PLSupplierAccountID { get; set; }
        public string SupplierAccountNumber { get; set; }
        public string SupplierAccountName { get; set; }
        public string SupplierAccountShortName { get; set; }
        public decimal? AccountBalance { get; set; }
        public decimal? CreditLimit { get; set; }
        public long SYSCurrencyID { get; set; }
        public long SYSExchangeRateTypeID { get; set; }
        public long SYSCountryCodeID { get; set; }
        public long? PLFactorHouseID { get; set; }
        public long DefaultSYSTaxRateID { get; set; }
        public string TaxRegistrationNumber { get; set; }
        public short MonthsToKeepTransactionsFor { get; set; }
        public string DefaultOrderPriority { get; set; }
        public string DefaultNominalAccountNumber { get; set; }
        public string DefaultNominalCostCentre { get; set; }
        public string DefaultNominalDepartment { get; set; }
        public long SYSAccountTypeID { get; set; }
        public long PLPaymentGroupID { get; set; }
        public decimal EarlySettlementDiscountPercent { get; set; }
        public short DaysEarlySettlementDiscApplies { get; set; }
        public short PaymentTermsInDays { get; set; }
        public long SYSPaymentTermsBasisID { get; set; }
        public bool AccountIsOnHold { get; set; }
        public decimal ValueOfCurrentOrdersInPOP { get; set; }
        public DateTime? DateAccountDetailsLastChanged { get; set; }
        public DateTime? DateOfLastTransaction { get; set; }
        public string EuroAccountNumberCopiedFromTo { get; set; }
        public DateTime? DateEuroAccountCopied { get; set; }
        public bool UseTransactionEMail { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public long? SYSCreditBureauID { get; set; }
        public long? SYSCreditPositionID { get; set; }
        public string TradingTerms { get; set; }
        public string CreditReference { get; set; }
        public DateTime? AccountOpened { get; set; }
        public DateTime? LastCreditReview { get; set; }
        public DateTime? NextCreditReview { get; set; }
        public DateTime? ApplicationDate { get; set; }
        public DateTime? DateReceived { get; set; }
        public bool TermsAgreed { get; set; }
        public string SpareText1 { get; set; }
        public string SpareText2 { get; set; }
        public string SpareText3 { get; set; }
        public decimal SpareNumber1 { get; set; }
        public decimal SpareNumber2 { get; set; }
        public decimal SpareNumber3 { get; set; }
        public DateTime? SpareDate1 { get; set; }
        public DateTime? SpareDate2 { get; set; }
        public DateTime? SpareDate3 { get; set; }
        public bool SpareBit1 { get; set; }
        public bool SpareBit2 { get; set; }
        public bool SpareBit3 { get; set; }
    }
}