// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class vw_RepSubContractAdviceNote
    {
        public string AdviceNoteNumber { get; set; }
        public string SupplierRef { get; set; }
        public string Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Address_3 { get; set; }
        public string Address_4 { get; set; }
        public string Address_5 { get; set; }
        public string ContactName { get; set; }
        public DateTime? DespatchDate { get; set; }
        public DateTime? DueDate { get; set; }
        public string WorksOrderNumber { get; set; }
        public string ProcessReference { get; set; }
        public string ProcessDescription { get; set; }
        public string SubContDetails { get; set; }
        public decimal? Quantity { get; set; }
        public string Source { get; set; }
        public string SuppJobRef { get; set; }
        public long OpID { get; set; }
        public long WoID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string Postcode { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public long CountryID { get; set; }
        public string CountryName { get; set; }
        public long SalutationID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Salutation { get; set; }
        public string CondensedAddress { get; set; }
    }
}