// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class vw_RepNominal
    {
        public long NLNominalAccountID { get; set; }
        public long NLAccountNumberCostCentreID { get; set; }
        public long NLDepartmentID { get; set; }
        public long? NLAccountReportCategoryID { get; set; }
        public long NLAccountTypeID { get; set; }
        public long NLCostCentreID { get; set; }
        public string ConsolidatedAccountNumber { get; set; }
        public string ConsolidatedCostCentre { get; set; }
        public string ConsolidatedDepartment { get; set; }
        public long? ParentNLNominalAccountID { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountCostCentre { get; set; }
        public string AccountDepartment { get; set; }
        public int PeriodsToKeepTransactions { get; set; }
        public bool AllowJournalsToBePosted { get; set; }
        public bool DisplayBalancesInSelectionList { get; set; }
        public bool PostBatchTotalsOnly { get; set; }
        public decimal CreditYearToDate { get; set; }
        public decimal DebitYearToDate { get; set; }
        public decimal ConsolidatedAdjustment { get; set; }
        public decimal BroughtForwardBalance { get; set; }
    }
}