// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class WopAllocationLine
    {
        public WopAllocationLine()
        {
            WopAllocationBalances = new HashSet<WopAllocationBalance>();
        }

        public long WopAllocationLineID { get; set; }
        public long? WopComponentLineID { get; set; }
        public string StockCode { get; set; }
        public string Description { get; set; }
        public decimal AllocationQuantity { get; set; }
        public long WarehouseID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual WopComponentLine WopComponentLine { get; set; }
        public virtual ICollection<WopAllocationBalance> WopAllocationBalances { get; set; }
    }
}