// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class WopBuildProductNominalPosting
    {
        public long WopBuildProductNominalPostingID { get; set; }
        public long WopBuildProductID { get; set; }
        public bool DebitTransaction { get; set; }
        public decimal Cost { get; set; }
        public long NominalAccountID { get; set; }
        public string NominalAccountNumber { get; set; }
        public string NominalAccountCostCentre { get; set; }
        public string NominalAccountDepartment { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public long? URN { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual WopBuildProduct WopBuildProduct { get; set; }
    }
}