// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class WopBomComponentLineLink
    {
        public long WopBomComponentLineLinkID { get; set; }
        public long BomComponentLineID { get; set; }
        public long WopComponentLineID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BomComponentLine BomComponentLine { get; set; }
        public virtual WopComponentLine WopComponentLine { get; set; }
    }
}