// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class WorksOrderImage
    {
        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public byte[] Picture { get; set; }

        public virtual WorksOrder Header { get; set; }
    }
}