// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class WorksOrder
    {
        public WorksOrder()
        {
            MFGIssues = new HashSet<MFGIssue>();
            MFGPOPOrderReturnLines = new HashSet<MFGPOPOrderReturnLine>();
            WorksOrderAllocIssues = new HashSet<WorksOrderAllocIssue>();
            WorksOrderAttachedDocuments = new HashSet<WorksOrderAttachedDocument>();
            WorksOrderFinishedProducts = new HashSet<WorksOrderFinishedProduct>();
            WorksOrderImages = new HashSet<WorksOrderImage>();
            WorksOrderSalesOrders = new HashSet<WorksOrderSalesOrder>();
            WorksOrderSerialNumbers = new HashSet<WorksOrderSerialNumber>();
            WorksOrderTrackings = new HashSet<WorksOrderTracking>();
        }

        public long ID { get; set; }
        public string WorksOrderNumber { get; set; }
        public string BomReference { get; set; }
        public string BomDescription { get; set; }
        public DateTime? DateEntered { get; set; }
        public string Status { get; set; }
        public decimal QtyRequired { get; set; }
        public decimal QtyFinished { get; set; }
        public string Notes { get; set; }
        public DateTime? LastCosted { get; set; }
        public decimal TotalCost { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal SuggestedSellingPrice { get; set; }
        public decimal IssueCost { get; set; }
        public decimal LabourCost { get; set; }
        public decimal MachineRun { get; set; }
        public decimal MachineSet { get; set; }
        public decimal MaterialCost { get; set; }
        public bool Printed { get; set; }
        public decimal QtyCostedFor { get; set; }
        public decimal QtyScrapped { get; set; }
        public string ReissueWO { get; set; }
        public string ScrapReason { get; set; }
        public decimal StandardMaterialCost { get; set; }
        public decimal SubContract { get; set; }
        public decimal ToolingCost { get; set; }
        public decimal ActLabourCost { get; set; }
        public decimal ActMachineCost { get; set; }
        public decimal ActSetupCost { get; set; }
        public decimal ActToolingCost { get; set; }
        public decimal ActSubContCost { get; set; }
        public decimal ActStdMatCost { get; set; }
        public bool JobItem { get; set; }
        public long? JobID { get; set; }
        public decimal ActSuggSellPrice { get; set; }
        public decimal CostsTransStock { get; set; }
        public string AccToDebit { get; set; }
        public decimal PostedMatCost { get; set; }
        public decimal PostedLabCost { get; set; }
        public decimal PostedMachCost { get; set; }
        public decimal PostedSetupCost { get; set; }
        public decimal PostedToolingCost { get; set; }
        public decimal PostedSubContCost { get; set; }
        public string Custom_1 { get; set; }
        public string Custom_2 { get; set; }
        public string Custom_3 { get; set; }
        public string ImageForWoDocs { get; set; }
        public int NumberLabels { get; set; }
        public DateTime? LastCompletedDate { get; set; }
        public decimal CostPcnt { get; set; }
        public string AnalysisCode_1 { get; set; }
        public string AnalysisCode_2 { get; set; }
        public string AnalysisCode_3 { get; set; }
        public string AnalysisCode_4 { get; set; }
        public string AnalysisCode_5 { get; set; }
        public string ProjectNumber { get; set; }
        public short PcntComplete { get; set; }
        public string WorksNumber { get; set; }
        public bool BackFlushed { get; set; }
        public int PrintSessionID { get; set; }
        public string EnteredBy { get; set; }
        public string Salesperson { get; set; }
        public bool? IncludeInMrp { get; set; }
        public DateTime? DueDate { get; set; }
        public bool IncludeInMrpDemand { get; set; }
        public bool ComponentsChanged { get; set; }
        public bool ExcludeFromProjection { get; set; }
        public bool ExcludeFromPlanner { get; set; }
        public DateTime? DueLessSafety { get; set; }
        public int Priority { get; set; }
        public string LinkedTo { get; set; }
        public string Warehouse { get; set; }
        public decimal PostedUnplannedCost { get; set; }
        public decimal ActStdUnplannedCost { get; set; }
        public bool UseCompletionWarehouse { get; set; }
        public decimal? ScrapFactor { get; set; }
        public string StockUnitName { get; set; }
        public long WipNominalID { get; set; }
        public long? MfgAllocID { get; set; }
        public long Bin { get; set; }
        public decimal TotalMatOverhead { get; set; }
        public decimal TotalLabourOverhead { get; set; }
        public decimal TotalMachineOverhead { get; set; }
        public long? SOPOrderReturnLineID { get; set; }
        public decimal ActSubContVariance { get; set; }
        public bool? ComponentTraceability { get; set; }
        public string BOMRevision { get; set; }
        public decimal? QtyOutstanding { get; set; }
        public decimal? OsCostsToBePosted { get; set; }
        public string PlanPeriod { get; set; }
        public decimal ActualMaterialOverhead { get; set; }
        public decimal ActualLabourOverhead { get; set; }
        public decimal ActualMachineOverhead { get; set; }
        public decimal LineUnitPrecision { get; set; }
        public decimal StockUnitPrecision { get; set; }
        public decimal MultipleOfStockUnit { get; set; }
        public long? StockItemUnitID { get; set; }
        public string SalespersonFirstName { get; set; }
        public string SalespersonMiddleName { get; set; }
        public string SalespersonLastName { get; set; }
        public string SalespersonPreMigratedData { get; set; }
        public long SalespersonSalutationID { get; set; }
        public decimal MultipleOfLineUnit { get; set; }
        public decimal? ActUnitCost { get; set; }
        public string PipelineData { get; set; }

        public virtual Salutation SalespersonSalutation { get; set; }
        public virtual ICollection<MFGIssue> MFGIssues { get; set; }
        public virtual ICollection<MFGPOPOrderReturnLine> MFGPOPOrderReturnLines { get; set; }
        public virtual ICollection<WorksOrderAllocIssue> WorksOrderAllocIssues { get; set; }
        public virtual ICollection<WorksOrderAttachedDocument> WorksOrderAttachedDocuments { get; set; }
        public virtual ICollection<WorksOrderFinishedProduct> WorksOrderFinishedProducts { get; set; }
        public virtual ICollection<WorksOrderImage> WorksOrderImages { get; set; }
        public virtual ICollection<WorksOrderSalesOrder> WorksOrderSalesOrders { get; set; }
        public virtual ICollection<WorksOrderSerialNumber> WorksOrderSerialNumbers { get; set; }
        public virtual ICollection<WorksOrderTracking> WorksOrderTrackings { get; set; }
    }
}