// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.ReportEngine.Models.Sage
{
    public partial class WTEProjectItemExpenseFilteredMRUSearchView
    {
        public long? PCProjectItemID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public int? MMSUserID { get; set; }
        public DateTime? MaxDateTimeCreated { get; set; }
    }
}