// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.API.Models
{
    public partial class EmailTemplate
    {
        public string TemplateName { get; set; }
        public string Template { get; set; }
    }
}