// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.API.Models
{
    public partial class TicketSubscription
    {
        public int SubID { get; set; }
        public int? SubTicketID { get; set; }
        public int? SubUsrID { get; set; }
    }
}