// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.API.Models
{
    public partial class vw_KPI_GoodsIn
    {
        public DateTime? DateReceived { get; set; }
        public string StockCode { get; set; }
        public int? QtyReceived { get; set; }
        public string ContractName { get; set; }
    }
}