//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWKStockHeader
    {
        public int StkID { get; set; }
        public string Description { get; set; }
        public string StockCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
    }
}
