//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Api.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSetting
    {
        public int ID { get; set; }
        public string MainWarehouse { get; set; }
        public string SabreStockWarehouse { get; set; }
        public string MainRepairablesWarehouse { get; set; }
        public string VTGRepairablesWarehouse { get; set; }
    }
}
