// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.ReportEngine.Models.Titan
{
    public partial class Document
    {
        public int DocID { get; set; }
        public int? TicketID { get; set; }
        public int? ActionID { get; set; }
        public string DocumentName { get; set; }
        public string FilePath { get; set; }
        public int? ConID { get; set; }
        public int? DocumentType { get; set; }
        public string LastUpdatedBy { get; set; }
        public DateTime? DateLastUpdated { get; set; }
        public int? AWKID { get; set; }
        public string AWKImage { get; set; }
        public string FileType { get; set; }
    }
}