// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.ReportEngine.Models.Titan
{
    public partial class ETrack
    {
        public int id { get; set; }
        public string EmailID { get; set; }
        public int? ViewCounter { get; set; }
        public DateTime? DateSent { get; set; }
        public string EmailTo { get; set; }
        public DateTime? DateOpened { get; set; }
        public int? ReportType { get; set; }
        public string SentBy { get; set; }
        public int? ContractID { get; set; }
    }
}