// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.ReportEngine.Models.Titan
{
    public partial class HoldNote
    {
        public int HNID { get; set; }
        public string CatNo { get; set; }
        public string Description { get; set; }
        public string SOR { get; set; }
        public string AccountName { get; set; }
        public int? AWKQty { get; set; }
        public string HoldNoteType { get; set; }
        public string HoldNotePrefix { get; set; }
        public string Fault { get; set; }
        public string RaisedBy { get; set; }
        public DateTime? DateRasied { get; set; }
        public int? AWKID { get; set; }
        public string WONumber { get; set; }
    }
}