// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.ReportEngine.Models.Titan
{
    public partial class LookUpAWKFault
    {
        public int id { get; set; }
        public string LookupText { get; set; }
    }
}