// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Titan.ReportEngine.Models.Titan
{
    public partial class StockHeader
    {
        public int StkID { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public byte[] StkImageData { get; set; }
        public string StkContentType { get; set; }
        public string DirtyStockCode { get; set; }
        public string StockCode { get; set; }
    }
}