// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class AnalysisCode
    {
        public AnalysisCode()
        {
            AnalysisCodeValues = new HashSet<AnalysisCodeValue>();
        }

        public long AnalysisCodeID { get; set; }
        public string Name { get; set; }
        public bool AllowOvertype { get; set; }
        public bool AllowNewOnEntry { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<AnalysisCodeValue> AnalysisCodeValues { get; set; }
    }
}