// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class AuditTrailView
    {
        public long UniqueReferenceNumber { get; set; }
        public string Source { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string NominalAccountNumber { get; set; }
        public string CostCentre { get; set; }
        public string Department { get; set; }
        public string Narrative { get; set; }
        public DateTime? TransactionDate { get; set; }
        public string Reference { get; set; }
        public string SecondReference { get; set; }
        public decimal NetValue { get; set; }
        public decimal TaxValue { get; set; }
        public short? Code { get; set; }
        public string Type { get; set; }
        public long SYSAuditTrailID { get; set; }
        public string TradingNominalAnalysisCode { get; set; }
    }
}