// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BinItem
    {
        public BinItem()
        {
            AllocationBalances = new HashSet<AllocationBalance>();
            MFGAllocations = new HashSet<MFGAllocation>();
            MFGIssues = new HashSet<MFGIssue>();
            MovementBalances = new HashSet<MovementBalance>();
            POPRcptReturnLineArches = new HashSet<POPRcptReturnLineArch>();
            POPReceiptReturnLines = new HashSet<POPReceiptReturnLine>();
            StocktakeCountSheetItems = new HashSet<StocktakeCountSheetItem>();
            TraceableBinItems = new HashSet<TraceableBinItem>();
        }

        public long BinItemID { get; set; }
        public string BinName { get; set; }
        public long ItemID { get; set; }
        public long WarehouseItemID { get; set; }
        public DateTime? DateOfLastStockCount { get; set; }
        public decimal LastCostPrice { get; set; }
        public DateTime? OpeningBalanceDate { get; set; }
        public bool UnspecifiedBin { get; set; }
        public decimal ConfirmedQtyInStock { get; set; }
        public decimal UnconfirmedQtyInStock { get; set; }
        public decimal QuantityAllocatedSOP { get; set; }
        public decimal QuantityAllocatedStock { get; set; }
        public decimal QuantityAllocatedBOM { get; set; }
        public decimal QuantityReserved { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public string SpareText1 { get; set; }
        public string SpareText2 { get; set; }
        public string SpareText3 { get; set; }
        public decimal SpareNumber1 { get; set; }
        public decimal SpareNumber2 { get; set; }
        public decimal SpareNumber3 { get; set; }
        public DateTime? SpareDate1 { get; set; }
        public DateTime? SpareDate2 { get; set; }
        public DateTime? SpareDate3 { get; set; }
        public bool SpareBit1 { get; set; }
        public bool SpareBit2 { get; set; }
        public bool SpareBit3 { get; set; }
        public long AllocationPriority { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual StockItem Item { get; set; }
        public virtual WarehouseItem WarehouseItem { get; set; }
        public virtual ICollection<AllocationBalance> AllocationBalances { get; set; }
        public virtual ICollection<MFGAllocation> MFGAllocations { get; set; }
        public virtual ICollection<MFGIssue> MFGIssues { get; set; }
        public virtual ICollection<MovementBalance> MovementBalances { get; set; }
        public virtual ICollection<POPRcptReturnLineArch> POPRcptReturnLineArches { get; set; }
        public virtual ICollection<POPReceiptReturnLine> POPReceiptReturnLines { get; set; }
        public virtual ICollection<StocktakeCountSheetItem> StocktakeCountSheetItems { get; set; }
        public virtual ICollection<TraceableBinItem> TraceableBinItems { get; set; }
    }
}