// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BLBillLine
    {
        public BLBillLine()
        {
            BLBillLineInvoiceCreditLines = new HashSet<BLBillLineInvoiceCreditLine>();
            BLBillLinePostings = new HashSet<BLBillLinePosting>();
            BLBilledTransactions = new HashSet<BLBilledTransaction>();
        }

        public long BLBillLineID { get; set; }
        public long BLBillID { get; set; }
        public long BLBillLineTypeID { get; set; }
        public int LineSequenceNo { get; set; }
        public long? BLContractID { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitValue { get; set; }
        public long? SYSTaxRateID { get; set; }
        public decimal UnitDiscountValue { get; set; }
        public long? PCProjectCostItemID { get; set; }
        public string NominalAccountNumber { get; set; }
        public string NominalAccountCostCentre { get; set; }
        public string NominalAccountDepartment { get; set; }
        public decimal TotalNetValue { get; set; }
        public decimal TotalTaxValue { get; set; }
        public long? PCUnitOfMeasureID { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public long BLAmountOrPercentageID { get; set; }
        public long BLDiscountOrSurchargeID { get; set; }
        public decimal UnitDiscountPercent { get; set; }
        public string Description { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BLAmountOrPercentage BLAmountOrPercentage { get; set; }
        public virtual BLBill BLBill { get; set; }
        public virtual BLBillLineType BLBillLineType { get; set; }
        public virtual BLContract BLContract { get; set; }
        public virtual BLDiscountOrSurcharge BLDiscountOrSurcharge { get; set; }
        public virtual PCUnitOfMeasure PCUnitOfMeasure { get; set; }
        public virtual SYSTaxRate SYSTaxRate { get; set; }
        public virtual ICollection<BLBillLineInvoiceCreditLine> BLBillLineInvoiceCreditLines { get; set; }
        public virtual ICollection<BLBillLinePosting> BLBillLinePostings { get; set; }
        public virtual ICollection<BLBilledTransaction> BLBilledTransactions { get; set; }
    }
}