// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BomAllocation
    {
        public BomAllocation()
        {
            BomAllocationWarehouses = new HashSet<BomAllocationWarehouse>();
            BomAllocationWopOrderLinks = new HashSet<BomAllocationWopOrderLink>();
            WopOrders = new HashSet<WopOrder>();
        }

        public long BomAllocationID { get; set; }
        public DateTime AllocationDateTime { get; set; }
        public string AllocatedBy { get; set; }
        public string AllocationReference { get; set; }
        public string AllocationNumber { get; set; }
        public bool ReportShortagesForComponents { get; set; }
        public bool ReportShortagesForSubAssemblies { get; set; }
        public short SubassemblyTreatmentType { get; set; }
        public short ShortageFoundAction { get; set; }
        public long BomAllocationStatusID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BomAllocationStatus BomAllocationStatus { get; set; }
        public virtual BomBuildSession BomBuildSession { get; set; }
        public virtual ICollection<BomAllocationWarehouse> BomAllocationWarehouses { get; set; }
        public virtual ICollection<BomAllocationWopOrderLink> BomAllocationWopOrderLinks { get; set; }
        public virtual ICollection<WopOrder> WopOrders { get; set; }
    }
}