// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BOMBuildFinishedItem
    {
        public BOMBuildFinishedItem()
        {
            BOMBuildComponents = new HashSet<BOMBuildComponent>();
            InverseIsComponentOf = new HashSet<BOMBuildFinishedItem>();
            TraceBOMBuildFinItems = new HashSet<TraceBOMBuildFinItem>();
        }

        public long BOMBuildFinishedItemID { get; set; }
        public long BOMBuildID { get; set; }
        public long? BOMID { get; set; }
        public string BOMVersion { get; set; }
        public string BOMShortName { get; set; }
        public long? IsComponentOfID { get; set; }
        public bool IsIntermediateItem { get; set; }
        public decimal Quantity { get; set; }
        public decimal CostRollUp { get; set; }
        public long StockItemID { get; set; }
        public long BinItemID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BOM BOM { get; set; }
        public virtual BOMBuild BOMBuild { get; set; }
        public virtual BOMBuildFinishedItem IsComponentOf { get; set; }
        public virtual ICollection<BOMBuildComponent> BOMBuildComponents { get; set; }
        public virtual ICollection<BOMBuildFinishedItem> InverseIsComponentOf { get; set; }
        public virtual ICollection<TraceBOMBuildFinItem> TraceBOMBuildFinItems { get; set; }
    }
}