// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BOMCostItem
    {
        public BOMCostItem()
        {
            BOMCostItemUnits = new HashSet<BOMCostItemUnit>();
            BOMLineCheckedOuts = new HashSet<BOMLineCheckedOut>();
            BOMLines = new HashSet<BOMLine>();
        }

        public long BOMCostItemID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long BOMCostTypeID { get; set; }
        public decimal ChargeRate { get; set; }
        public long BaseUnitID { get; set; }
        public decimal OHAllocationRatio { get; set; }
        public string NominalAccountRef { get; set; }
        public string NominalCostCentre { get; set; }
        public string NominalDepartment { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual Old200BOMCostType BOMCostType { get; set; }
        public virtual BOMUnit BaseUnit { get; set; }
        public virtual ICollection<BOMCostItemUnit> BOMCostItemUnits { get; set; }
        public virtual ICollection<BOMLineCheckedOut> BOMLineCheckedOuts { get; set; }
        public virtual ICollection<BOMLine> BOMLines { get; set; }
    }
}