// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BOMCheckedOut
    {
        public BOMCheckedOut()
        {
            BOMLineCheckedOuts = new HashSet<BOMLineCheckedOut>();
            BOMs = new HashSet<BOM>();
        }

        public long BOMCheckedOutID { get; set; }
        public DateTime? CheckedOutOn { get; set; }
        public string CheckedOutByUserName { get; set; }
        public long BOMID { get; set; }
        public long StockItemID { get; set; }
        public string BOMVersion { get; set; }
        public string BOMShortName { get; set; }
        public string ChangeReference { get; set; }
        public bool IsOnHold { get; set; }
        public long? BOMReasonForHoldID { get; set; }
        public DateTime? HoldDate { get; set; }
        public long BOMStatusID { get; set; }
        public bool IsCostDirty { get; set; }
        public bool AutoOverheadComputation { get; set; }
        public decimal OverheadCost { get; set; }
        public decimal PerUnitMaterialCost { get; set; }
        public decimal PerUnitExpenseCost { get; set; }
        public decimal AverageRunSizeForBatch { get; set; }
        public decimal PerBatchExpenseCost { get; set; }
        public decimal TotalCost { get; set; }
        public string CreatedByUserName { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string LastAmendedByUserName { get; set; }
        public DateTime? LastamendedOn { get; set; }
        public bool HasComponentReferences { get; set; }
        public DateTime? CheckedOutTime { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual Old200BOMReasonForHold BOMReasonForHold { get; set; }
        public virtual BOMStatusType BOMStatus { get; set; }
        public virtual ICollection<BOMLineCheckedOut> BOMLineCheckedOuts { get; set; }
        public virtual ICollection<BOM> BOMs { get; set; }
    }
}