// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BomFinishedProduct
    {
        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public string ProductCode { get; set; }
        public decimal Quantity { get; set; }
        public bool? HoldQuantity { get; set; }
        public decimal CostPcnt { get; set; }

        public virtual BomHeader Header { get; set; }
    }
}