// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BomRevisionHistory
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public DateTime DateModified { get; set; }
        public string BuiltStockItemReference { get; set; }
        public string Revision { get; set; }
        public string Notes { get; set; }
        public bool Tentative { get; set; }
    }
}