// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BomVersionStatus
    {
        public BomVersionStatus()
        {
            BomCostSessions = new HashSet<BomCostSession>();
            BomRecords = new HashSet<BomRecord>();
        }

        public long BomVersionStatusID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<BomCostSession> BomCostSessions { get; set; }
        public virtual ICollection<BomRecord> BomRecords { get; set; }
    }
}