// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class BomVersionsHeader
    {
        public BomVersionsHeader()
        {
            BomVersionsAttachedDocuments = new HashSet<BomVersionsAttachedDocument>();
            BomVersionsComponents = new HashSet<BomVersionsComponent>();
            BomVersionsDrawings = new HashSet<BomVersionsDrawing>();
            BomVersionsImages = new HashSet<BomVersionsImage>();
            BomVersionsOperations = new HashSet<BomVersionsOperation>();
        }

        public long ID { get; set; }
        public string BomReference { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public decimal StandardMaterialCost { get; set; }
        public bool? TopLevel { get; set; }
        public string Standard { get; set; }
        public DateTime? Entered { get; set; }
        public DateTime? LastCosted { get; set; }
        public DateTime? LastUpdated { get; set; }
        public string Weight { get; set; }
        public string Per { get; set; }
        public string Carton { get; set; }
        public string CartonPer { get; set; }
        public decimal MaterialCost { get; set; }
        public decimal LabourCost { get; set; }
        public decimal MachineSet { get; set; }
        public decimal MachineRun { get; set; }
        public decimal SubContract { get; set; }
        public decimal ToolingCost { get; set; }
        public decimal TotalMatOverhead { get; set; }
        public decimal TotalLabourOverhead { get; set; }
        public decimal TotalMachineOverhead { get; set; }
        public decimal TotalOverheads { get; set; }
        public decimal TotalCost { get; set; }
        public decimal MarkUp { get; set; }
        public decimal QtyCostedFor { get; set; }
        public decimal SuggestedSellingPrice { get; set; }
        public decimal DefaultQty { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
        public string Custom_1 { get; set; }
        public string Custom_2 { get; set; }
        public string Custom_3 { get; set; }
        public string Custom_4 { get; set; }
        public string Custom_5 { get; set; }
        public string Custom_6 { get; set; }
        public string Custom_7 { get; set; }
        public string Custom_8 { get; set; }
        public string Custom_9 { get; set; }
        public string Custom_10 { get; set; }
        public string ImageForWoDocs { get; set; }
        public bool Phantom { get; set; }
        public string Revision { get; set; }
        public decimal CostPcnt { get; set; }
        public DateTime? CompOpTimeStamp { get; set; }
        public string AnalysisCode_1 { get; set; }
        public string AnalysisCode_2 { get; set; }
        public string AnalysisCode_3 { get; set; }
        public string AnalysisCode_4 { get; set; }
        public string AnalysisCode_5 { get; set; }
        public byte[] Timestamp { get; set; }
        public bool Private { get; set; }
        public bool OnHold { get; set; }
        public bool? ComponentTraceability { get; set; }
        public double? DefaultScrap { get; set; }
        public short VersionStatus { get; set; }

        public virtual ICollection<BomVersionsAttachedDocument> BomVersionsAttachedDocuments { get; set; }
        public virtual ICollection<BomVersionsComponent> BomVersionsComponents { get; set; }
        public virtual ICollection<BomVersionsDrawing> BomVersionsDrawings { get; set; }
        public virtual ICollection<BomVersionsImage> BomVersionsImages { get; set; }
        public virtual ICollection<BomVersionsOperation> BomVersionsOperations { get; set; }
    }
}