// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class CBBankFeedPostingInstruction
    {
        public long CBBankFeedPostingInstructionID { get; set; }
        public long CBBankFeedAccountPostingID { get; set; }
        public string Reference { get; set; }
        public string Value { get; set; }

        public virtual CBBankFeedAccountPosting CBBankFeedAccountPosting { get; set; }
    }
}