// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class CBBankStatement
    {
        public long CBBankStatementID { get; set; }
        public long CBAccountID { get; set; }
        public int PageNumber { get; set; }
        public DateTime StatementDate { get; set; }
        public decimal StatementOpeningBalance { get; set; }
        public decimal StatementClosingBalance { get; set; }
        public decimal StatementCBAccountBalance { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual CBAccount CBAccount { get; set; }
    }
}