// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class CBBankFeedTransaction
    {
        public CBBankFeedTransaction()
        {
            CBBankFeedAccountPostings = new HashSet<CBBankFeedAccountPosting>();
        }

        public long CBBankFeedTransactionID { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public int CBBankFeedTransactionTypeID { get; set; }
        public DateTime PostingDate { get; set; }
        public int CBBankFeedReconciliationStatusID { get; set; }
        public string CurrencyCode { get; set; }
        public string TransactionStatus { get; set; }
        public string TransactionGuid { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public long CBAccountID { get; set; }
        public long? SageBankFeedTransactionID { get; set; }
        public string SageBankFeedTransactionType { get; set; }
        public bool IsApprovalRequired { get; set; }
        public string RuleName { get; set; }
        public long CBBankFeedProcessStatusID { get; set; }
        public long? AssociatedURN { get; set; }
        public string PostingErrorMessage { get; set; }
        public string PayeeSortCode { get; set; }
        public string PayeeAccountNumber { get; set; }
        public string PostingCode { get; set; }
        public string PostingName { get; set; }
        public string PostingType { get; set; }

        public virtual CBAccount CBAccount { get; set; }
        public virtual CBBankFeedProcessStatus CBBankFeedProcessStatus { get; set; }
        public virtual CBBankFeedReconciliationStatus CBBankFeedReconciliationStatus { get; set; }
        public virtual CBBankFeedTransactionType CBBankFeedTransactionType { get; set; }
        public virtual ICollection<CBBankFeedAccountPosting> CBBankFeedAccountPostings { get; set; }
    }
}