// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class CBPostedAccountTran
    {
        public CBPostedAccountTran()
        {
            CBGroupHistCustomerTrans = new HashSet<CBGroupHistCustomerTran>();
            CBGroupHistSupplierTrans = new HashSet<CBGroupHistSupplierTran>();
            CBGroupPostedCustomerTrans = new HashSet<CBGroupPostedCustomerTran>();
            CBGroupPostedSupplierTrans = new HashSet<CBGroupPostedSupplierTran>();
            PLProposedPayments = new HashSet<PLProposedPayment>();
        }

        public long CBPostedAccountTranID { get; set; }
        public long CBAccountID { get; set; }
        public long CBTranTypeID { get; set; }
        public DateTime TransactionDate { get; set; }
        public string TransactionReference { get; set; }
        public string SecondReference { get; set; }
        public decimal ChequeValue { get; set; }
        public decimal ChequeDiscountValue { get; set; }
        public long ChequeSYSCurrencyID { get; set; }
        public decimal ChequeToBaseCurrExchangeRate { get; set; }
        public decimal ChequeToAccountExchangeRate { get; set; }
        public DateTime PostedDate { get; set; }
        public long Source { get; set; }
        public long UniqueReferenceNumber { get; set; }
        public string UserName { get; set; }
        public int UserNumber { get; set; }
        public int StandingOrderDDReference { get; set; }
        public string NominalOrTraderAccountNumber { get; set; }
        public string NominalAccountCostCentre { get; set; }
        public string NominalAccountDepartment { get; set; }
        public string ChequeDescription { get; set; }
        public decimal StatementValue { get; set; }
        public int? StatementPageNumber { get; set; }
        public DateTime? LastStatementDate { get; set; }
        public long? CBDirectDebitTranID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public long? NominalAccountingPeriodID { get; set; }
        public string QueryReason { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public string SagePaymentsIdentifier { get; set; }
        public long SagePaymentsTransactionStatusID { get; set; }
        public bool SagePaymentsHasNote { get; set; }
        public int? BankFeedReconciliationStatus { get; set; }
        public long SYSCorrectionTranTypeID { get; set; }

        public virtual CBAccount CBAccount { get; set; }
        public virtual CBDirectDebitTran CBDirectDebitTran { get; set; }
        public virtual CBTranType CBTranType { get; set; }
        public virtual SYSCurrency ChequeSYSCurrency { get; set; }
        public virtual SYSAccountingPeriod NominalAccountingPeriod { get; set; }
        public virtual SYSCorrectionTranType SYSCorrectionTranType { get; set; }
        public virtual SagePaymentsTransactionStatus SagePaymentsTransactionStatus { get; set; }
        public virtual CBDraftStatementPostTranLink CBDraftStatementPostTranLink { get; set; }
        public virtual ICollection<CBGroupHistCustomerTran> CBGroupHistCustomerTrans { get; set; }
        public virtual ICollection<CBGroupHistSupplierTran> CBGroupHistSupplierTrans { get; set; }
        public virtual ICollection<CBGroupPostedCustomerTran> CBGroupPostedCustomerTrans { get; set; }
        public virtual ICollection<CBGroupPostedSupplierTran> CBGroupPostedSupplierTrans { get; set; }
        public virtual ICollection<PLProposedPayment> PLProposedPayments { get; set; }
    }
}