// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class CRMIntegrationType
    {
        public CRMIntegrationType()
        {
            CRMIntegrationSettings = new HashSet<CRMIntegrationSetting>();
        }

        public long CRMIntegrationTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<CRMIntegrationSetting> CRMIntegrationSettings { get; set; }
    }
}