// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class DefaultPricingSourceType
    {
        public DefaultPricingSourceType()
        {
            StockItemSuppliers = new HashSet<StockItemSupplier>();
        }

        public long DefaultPricingSourceTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<StockItemSupplier> StockItemSuppliers { get; set; }
    }
}