// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class EDULocalEducationAuthority
    {
        public EDULocalEducationAuthority()
        {
            SYSCompanies = new HashSet<SYSCompany>();
        }

        public long EDULocalEducationAuthorityID { get; set; }
        public string Name { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public bool EnforcesMandatoryNominalCodes { get; set; }

        public virtual ICollection<SYSCompany> SYSCompanies { get; set; }
    }
}