// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class EmployeeRate
    {
        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public decimal Rate { get; set; }
        public string Debit { get; set; }
        public string Credit { get; set; }

        public virtual Employee Header { get; set; }
    }
}