// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class EventLog
    {
        public long EventLogID { get; set; }
        public DateTime DateOfEvent { get; set; }
        public DateTime TimeOfEvent { get; set; }
        public long EventLogTypeID { get; set; }
        public string Source { get; set; }
        public string Area { get; set; }
        public string Description { get; set; }
        public short Code { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual EventLogType EventLogType { get; set; }
    }
}