// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class ForecastSetting
    {
        public long ForecastSettingID { get; set; }
        public int DefaultNumberOfPeriods { get; set; }
        public string FileBasePath { get; set; }
        public string ImportWorksheetName { get; set; }
        public string StockCodeColumnHeading { get; set; }
        public string CustomerColumnHeading { get; set; }
        public int FirstDateIndexPosition { get; set; }
        public string WarehouseColumnHeading { get; set; }
        public long? DefaultWarehouseID { get; set; }
        public int WeekStartsOn { get; set; }
        public bool BucketRecalcFlag { get; set; }
        public bool SOPLookaheadWeekly { get; set; }
        public bool SOPLookaheadReqDelDate { get; set; }
        public bool UseSOPLineWarehouse { get; set; }

        public virtual Warehouse DefaultWarehouse { get; set; }
    }
}