// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class INCREASE_vw_ContactDetailsforEstimate
    {
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Role { get; set; }
        public long SLCustomerAccountID { get; set; }
    }
}