// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class INCREASE_BOMOP_EstTime
    {
        public string Reference { get; set; }
        public string Operation_Reference { get; set; }
        public decimal? Total_Mins { get; set; }
    }
}