// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class INCREASE_vw_SalesOrderLinesWithoutPromiseDate
    {
        public string DocumentNo { get; set; }
        public DateTime? DocumentDate { get; set; }
        public long LineTypeID { get; set; }
        public DateTime? PromisedDeliveryDate { get; set; }
        public bool? CreateWorksOrder { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
    }
}