// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class INCREASE_vw_ForecastUniqueCustAndProd
    {
        public long? ForecastID { get; set; }
        public long? ItemID { get; set; }
        public long? SLCustomerAccountID { get; set; }
    }
}