// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class INCREASE_IssuedCost
    {
        public string BomReference { get; set; }
        public string WorksOrderNumber { get; set; }
        public decimal QtyFinished { get; set; }
        public decimal IssueCost { get; set; }
        public double? Sequence { get; set; }
        public string Code { get; set; }
        public decimal CostValue { get; set; }
    }
}