// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class JobAllocIssue
    {
        public JobAllocIssue()
        {
            JobOpComponents = new HashSet<JobOpComponent>();
        }

        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public decimal Required { get; set; }
        public decimal Allocated { get; set; }
        public decimal Issued { get; set; }
        public decimal Scrapped { get; set; }
        public string BinLocation { get; set; }
        public string ReasonForScrap { get; set; }
        public string StockUnitName { get; set; }
        public long? MfgAllocLineID { get; set; }
        public decimal LineUnitPrecision { get; set; }
        public decimal StockUnitPrecision { get; set; }
        public decimal MultipleOfStockUnit { get; set; }
        public long? StockItemUnitID { get; set; }
        public decimal MultipleOfLineUnit { get; set; }

        public virtual JobStage Header { get; set; }
        public virtual ICollection<JobOpComponent> JobOpComponents { get; set; }
    }
}