// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class JobSalesInvoiceItem
    {
        public long ID { get; set; }
        public long? HeaderID { get; set; }
        public DateTime? DelDate { get; set; }
        public long? DeptNumber { get; set; }
        public string Description { get; set; }
        public decimal DiscAmount { get; set; }
        public decimal DiscRate { get; set; }
        public decimal FullNetAmount { get; set; }
        public string JobRef { get; set; }
        public decimal NetAmount { get; set; }
        public string NominalCode { get; set; }
        public decimal TaxAmount { get; set; }
        public long? TaxCode { get; set; }
        public bool RetnLine { get; set; }
        public DateTime? RetnDate { get; set; }
        public DateTime? RetnExpiryDate { get; set; }
        public string RetnNomCode { get; set; }
        public long? RetnDeptNumber { get; set; }
        public string ServiceText { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }

        public virtual JobSalesInvoiceHeader Header { get; set; }
    }
}