// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class LandedCostsType
    {
        public LandedCostsType()
        {
            POPOrderReturnLineArches = new HashSet<POPOrderReturnLineArch>();
            POPOrderReturnLines = new HashSet<POPOrderReturnLine>();
            ProductGroups = new HashSet<ProductGroup>();
            StockItemSuppliers = new HashSet<StockItemSupplier>();
            StockItems = new HashSet<StockItem>();
        }

        public long LandedCostsTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<POPOrderReturnLineArch> POPOrderReturnLineArches { get; set; }
        public virtual ICollection<POPOrderReturnLine> POPOrderReturnLines { get; set; }
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
        public virtual ICollection<StockItemSupplier> StockItemSuppliers { get; set; }
        public virtual ICollection<StockItem> StockItems { get; set; }
    }
}