// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class MFGAllocation
    {
        public MFGAllocation()
        {
            MFGAllocationLines = new HashSet<MFGAllocationLine>();
            MfgBomAllocHierarchies = new HashSet<MfgBomAllocHierarchy>();
        }

        public long ID { get; set; }
        public DateTime? DateTime { get; set; }
        public string BuiltItemStockCode { get; set; }
        public string AllocationReference { get; set; }
        public string AllocationDescription { get; set; }
        public short? MfgModule { get; set; }
        public decimal BuiltItemQuantity { get; set; }
        public long? BuiltItemBin { get; set; }

        public virtual BinItem BuiltItemBinNavigation { get; set; }
        public virtual ICollection<MFGAllocationLine> MFGAllocationLines { get; set; }
        public virtual ICollection<MfgBomAllocHierarchy> MfgBomAllocHierarchies { get; set; }
    }
}