// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class MFGWarehouse
    {
        public long MFGWarehouseID { get; set; }
        public long WarehouseID { get; set; }
        public bool? IsComponentSource { get; set; }
        public long? MFGContactID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual MFGContact MFGContact { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}