// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class MFGWoCompletion
    {
        public MFGWoCompletion()
        {
            MFGTraceableBuiltItems = new HashSet<MFGTraceableBuiltItem>();
        }

        public long ID { get; set; }
        public long? WOID { get; set; }
        public string Reference { get; set; }
        public string ItemCode { get; set; }
        public decimal Quantity { get; set; }
        public DateTime? DateTime { get; set; }

        public virtual ICollection<MFGTraceableBuiltItem> MFGTraceableBuiltItems { get; set; }
    }
}