// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class MRPReplenishmentRulesType
    {
        public MRPReplenishmentRulesType()
        {
            MFGStockItems = new HashSet<MFGStockItem>();
        }

        public long MRPReplenishmentRulesTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<MFGStockItem> MFGStockItems { get; set; }
    }
}