// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class MsmCostHeadingType
    {
        public MsmCostHeadingType()
        {
            BomCostSessionTotals = new HashSet<BomCostSessionTotal>();
            BomCosts = new HashSet<BomCost>();
            MsmCostHeadings = new HashSet<MsmCostHeading>();
        }

        public long MsmCostHeadingTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<BomCostSessionTotal> BomCostSessionTotals { get; set; }
        public virtual ICollection<BomCost> BomCosts { get; set; }
        public virtual ICollection<MsmCostHeading> MsmCostHeadings { get; set; }
    }
}