// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class MsmSearchCondition
    {
        public MsmSearchCondition()
        {
            MsmSearchLines = new HashSet<MsmSearchLine>();
        }

        /// <summary>
        /// Primary Key.
        /// </summary>
        public long MsmSearchConditionID { get; set; }
        /// <summary>
        /// The name of the condition.
        /// </summary>
        public string Name { get; set; }

        public virtual ICollection<MsmSearchLine> MsmSearchLines { get; set; }
    }
}