// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class NLConsolidationItem
    {
        public long NLConsolidationItemID { get; set; }
        public long NLConsolidationID { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountCostCentre { get; set; }
        public string AccountDepartment { get; set; }
        public string ConsolidatedAccountNumber { get; set; }
        public string ConsolidatedCostCentre { get; set; }
        public string ConsolidatedDepartment { get; set; }
        public decimal Amount { get; set; }

        public virtual NLConsolidation NLConsolidation { get; set; }
    }
}