// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class NLFinancialReportCategory
    {
        public long NLFinancialReportCategoryID { get; set; }
        public long NLAccountReportTypeID { get; set; }
        public long NLFinancialReportRowID { get; set; }
        public long NLAccountReportCategoryID { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual NLAccountReportCategory NLAccountReportCategory { get; set; }
        public virtual NLAccountReportType NLAccountReportType { get; set; }
        public virtual NLFinancialReportRow NLFinancialReportRow { get; set; }
    }
}