// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class NLFinancialReportJoinVw
    {
        public long NLFinancialReportRowID { get; set; }
        public long? NLFinancialReportCategoryID { get; set; }
        public long? NLAccountReportCategoryID { get; set; }
    }
}