// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class NLLayoutPositionType
    {
        public NLLayoutPositionType()
        {
            NLFinancialReportRows = new HashSet<NLFinancialReportRow>();
        }

        public long NLLayoutPositionTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<NLFinancialReportRow> NLFinancialReportRows { get; set; }
    }
}