// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class NLNominalTranType
    {
        public NLNominalTranType()
        {
            NLDeferredNominalTrans = new HashSet<NLDeferredNominalTran>();
            NLPendNominalTrans = new HashSet<NLPendNominalTran>();
            NLPostedNominalTrans = new HashSet<NLPostedNominalTran>();
            SYSCorrections = new HashSet<SYSCorrection>();
        }

        public long NLNominalTranTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<NLDeferredNominalTran> NLDeferredNominalTrans { get; set; }
        public virtual ICollection<NLPendNominalTran> NLPendNominalTrans { get; set; }
        public virtual ICollection<NLPostedNominalTran> NLPostedNominalTrans { get; set; }
        public virtual ICollection<SYSCorrection> SYSCorrections { get; set; }
    }
}