// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class NonProductiveTime
    {
        public NonProductiveTime()
        {
            NonProductiveBreakdowns = new HashSet<NonProductiveBreakdown>();
        }

        public long ID { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }

        public virtual ICollection<NonProductiveBreakdown> NonProductiveBreakdowns { get; set; }
    }
}