// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PaymentInvCredLineType
    {
        public PaymentInvCredLineType()
        {
            SOPPaymentInvCredLineArches = new HashSet<SOPPaymentInvCredLineArch>();
            SOPPaymentInvCredLines = new HashSet<SOPPaymentInvCredLine>();
        }

        public long PaymentInvCredLineTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SOPPaymentInvCredLineArch> SOPPaymentInvCredLineArches { get; set; }
        public virtual ICollection<SOPPaymentInvCredLine> SOPPaymentInvCredLines { get; set; }
    }
}