// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PCCostItemTypeIntegrateSetting
    {
        public long PCCostItemTypeIntegrateSettingID { get; set; }
        public long PCCostItemTypeID { get; set; }
        public long PCIntegrationOptionID { get; set; }
        public bool IntegrationEnabled { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual PCCostItemType PCCostItemType { get; set; }
        public virtual PCIntegrationOption PCIntegrationOption { get; set; }
    }
}