// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PCIntegrationOption
    {
        public PCIntegrationOption()
        {
            PCCostItemTypeIntegrateSettings = new HashSet<PCCostItemTypeIntegrateSetting>();
            PCDefaultIntegrationSettings = new HashSet<PCDefaultIntegrationSetting>();
        }

        public long PCIntegrationOptionID { get; set; }
        public long SYSModuleID { get; set; }
        public string Name { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSModule SYSModule { get; set; }
        public virtual ICollection<PCCostItemTypeIntegrateSetting> PCCostItemTypeIntegrateSettings { get; set; }
        public virtual ICollection<PCDefaultIntegrationSetting> PCDefaultIntegrationSettings { get; set; }
    }
}