// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PLAllocHeaderPostedEntryVw
    {
        public long PLAllocationHeaderID { get; set; }
        public DateTime AllocationDate { get; set; }
        public int UserNumber { get; set; }
        public string UserName { get; set; }
        public long PLSupplierAccountID { get; set; }
        public long UniqueReferenceNumber { get; set; }
        public long PLAllocationTypeID { get; set; }
        public bool IsComplete { get; set; }
        public long PLPostedSupplierTranID { get; set; }
        public string QueryCode { get; set; }
        public decimal? TotalDebitAllocation { get; set; }
    }
}