// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PlanMrpReplenishment
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public string Reference { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public DateTime? DueDate { get; set; }
        public long PoLineNumber { get; set; }
        public decimal QtyIn { get; set; }
        public decimal QtyUsed { get; set; }
        public string PoLineReference { get; set; }
        public long? WarehouseID { get; set; }
    }
}