// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PlanMrpOpeningStock
    {
        public long ID { get; set; }
        public string ProductCode { get; set; }
        public decimal PhysicalStock { get; set; }
        public long WarehouseID { get; set; }
        public DateTime? DateTimeRead { get; set; }
    }
}