// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PLAnalysisPeriod
    {
        public PLAnalysisPeriod()
        {
            PLSupplierPeriodValues = new HashSet<PLSupplierPeriodValue>();
        }

        public long PLAnalysisPeriodID { get; set; }
        public string PeriodReference { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<PLSupplierPeriodValue> PLSupplierPeriodValues { get; set; }
    }
}