// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PLFactorHouseContact
    {
        public long PLFactorHouseContactID { get; set; }
        public long PLFactorHouseID { get; set; }
        public string ContactAddress { get; set; }
        public string ContactName { get; set; }
        public long SYSContactTypeID { get; set; }
        public string Description { get; set; }
        public bool IsPrimary { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual PLFactorHouse PLFactorHouse { get; set; }
        public virtual SYSContactType SYSContactType { get; set; }
    }
}