// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PLSupplierBank
    {
        public long PLSupplierBankID { get; set; }
        public long PLSupplierAccountID { get; set; }
        public string SortCode { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string BankPaymentReference { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public string IBANNumber { get; set; }
        public string BICNumber { get; set; }
        public string RollNumber { get; set; }
        public string BACSReference { get; set; }
        public string AdditionalReference { get; set; }
        public string NonUKSortCode { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public string SagePaymentsIdentifier { get; set; }
        public string SagePaymentsNationalBankIdentifier { get; set; }

        public virtual PLSupplierAccount PLSupplierAccount { get; set; }
    }
}