// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class POPAuthAuditEventType
    {
        public POPAuthAuditEventType()
        {
            POPAuthAuditEvents = new HashSet<POPAuthAuditEvent>();
        }

        public long POPAuthAuditEventTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<POPAuthAuditEvent> POPAuthAuditEvents { get; set; }
    }
}