// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class POPInvCredDispute
    {
        public POPInvCredDispute()
        {
            POPInvoiceCreditLines = new HashSet<POPInvoiceCreditLine>();
            TEMMessages = new HashSet<TEMMessage>();
        }

        public long POPInvCredDisputeID { get; set; }
        public string DocumentNo { get; set; }
        public long POPInvoiceCreditTypeID { get; set; }
        public long SupplierID { get; set; }
        public long? POPDisputeCodeID { get; set; }
        public string DisputeComment { get; set; }
        public DateTime? DocumentDate { get; set; }
        public DateTime? DocumentDueDate { get; set; }
        public decimal InvCredGoodsValue { get; set; }
        public decimal InvCredTaxValue { get; set; }
        public decimal ExchangeRate { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual POPDisputeCode POPDisputeCode { get; set; }
        public virtual POPInvoiceCreditType POPInvoiceCreditType { get; set; }
        public virtual PLSupplierAccount Supplier { get; set; }
        public virtual ICollection<POPInvoiceCreditLine> POPInvoiceCreditLines { get; set; }
        public virtual ICollection<TEMMessage> TEMMessages { get; set; }
    }
}