// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class POPIntrastatVw
    {
        public string Code { get; set; }
        public string CommodityCode { get; set; }
        public DateTime? DocumentDate { get; set; }
        public string DocumentNo { get; set; }
        public string SupplierCountryCode { get; set; }
        public string DocumentCountryCode { get; set; }
        public string OriginCountryCode { get; set; }
        public bool SuppressNetMass { get; set; }
        public decimal Weight { get; set; }
        public decimal LineTotalValue { get; set; }
        public decimal LineTaxValue { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal DocumentDiscountPercent { get; set; }
        public int ArrivalDespatch { get; set; }
        public decimal ReceiptReturnQuantity { get; set; }
        public decimal StockUnitRcptRtnQuantity { get; set; }
        public decimal StockUnitLineQuantity { get; set; }
        public bool UsesSupplementaryUnit { get; set; }
        public decimal SupplementaryUnitConversionRatio { get; set; }
        public long POPOrderReturnID { get; set; }
        public long POPReceiptReturnLineID { get; set; }
        public DateTime? ReceiptReturnDate { get; set; }
        public short PrintSequenceNumber { get; set; }
        public bool SingleDeliveryAddress { get; set; }
        public long? PLSupplierAccountID { get; set; }
        public long ItemID { get; set; }
        public long IntrastatStatusID { get; set; }
        public string SupplierAccountNumber { get; set; }
        public decimal MultipleOfBaseUnit { get; set; }
    }
}