// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class POPOnOrderBalance
    {
        public long POPOnOrderBalanceID { get; set; }
        public decimal OnOrderQuantity { get; set; }
        public string SupplierReference { get; set; }
        public string SupplierName { get; set; }
        public string Reference { get; set; }
        public string SecondRef { get; set; }
        public DateTime OrderDate { get; set; }
        public long ItemID { get; set; }
        public long WarehouseItemID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual WarehouseItem WarehouseItem { get; set; }
        public virtual POPOnOrderLine POPOnOrderLine { get; set; }
    }
}