// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class POPReceiptReturn
    {
        public POPReceiptReturn()
        {
            POPReceiptReturnLines = new HashSet<POPReceiptReturnLine>();
        }

        public long POPReceiptReturnID { get; set; }
        public long POPReceiptReturnTypeID { get; set; }
        public string DocumentNo { get; set; }
        public DateTime? DocumentDate { get; set; }
        public string SupplierDocumentNo { get; set; }
        public DateTime? SupplierDocumentDate { get; set; }
        public string Narrative { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual POPReceiptReturnType POPReceiptReturnType { get; set; }
        public virtual ICollection<POPReceiptReturnLine> POPReceiptReturnLines { get; set; }
    }
}