// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class POPReceiptReturnLine
    {
        public POPReceiptReturnLine()
        {
            POPRcptRtnInvCredLines = new HashSet<POPRcptRtnInvCredLine>();
            TracePOPRcptRtnLines = new HashSet<TracePOPRcptRtnLine>();
        }

        public long POPReceiptReturnLineID { get; set; }
        public long POPReceiptReturnID { get; set; }
        public long POPOrderReturnLineID { get; set; }
        public string ReceiptReturnNo { get; set; }
        public string OrderReturnNo { get; set; }
        public decimal InvoiceCreditQuantity { get; set; }
        public long? BinItemID { get; set; }
        public string BinName { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public decimal ReceiptReturnQuantity { get; set; }
        public DateTime? ReceiptReturnDate { get; set; }
        public long? POPRcptRtnLineSourceID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public decimal StockUnitBuyingPrice { get; set; }
        public decimal ExchangeRate { get; set; }
        public bool LabelPrinted { get; set; }
        public long STKLabelPrintingOptionTypeID { get; set; }
        public long IntrastatStatusID { get; set; }
        public decimal StockUnitRcptRtnQuantity { get; set; }
        public decimal StockUnitInvCredQuantity { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual BinItem BinItem { get; set; }
        public virtual IntrastatStatus IntrastatStatus { get; set; }
        public virtual POPOrderReturnLine POPOrderReturnLine { get; set; }
        public virtual POPRcptRtnLineSource POPRcptRtnLineSource { get; set; }
        public virtual POPReceiptReturn POPReceiptReturn { get; set; }
        public virtual STKLabelPrintingOptionType STKLabelPrintingOptionType { get; set; }
        public virtual ICollection<POPRcptRtnInvCredLine> POPRcptRtnInvCredLines { get; set; }
        public virtual ICollection<TracePOPRcptRtnLine> TracePOPRcptRtnLines { get; set; }
    }
}