// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class POPToReorderItem
    {
        public POPToReorderItem()
        {
            POPToReorderWarehouses = new HashSet<POPToReorderWarehouse>();
        }

        public long POPToReorderItemID { get; set; }
        public long ItemID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string StockUnit { get; set; }
        public decimal QuantityRequired { get; set; }
        public decimal QuantityConfirmed { get; set; }
        public decimal ConfirmedPurchaseValue { get; set; }
        public long ToReorderItemStatusID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual StockItem Item { get; set; }
        public virtual POPToReorderItemStatus ToReorderItemStatus { get; set; }
        public virtual ICollection<POPToReorderWarehouse> POPToReorderWarehouses { get; set; }
    }
}