// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class PriceBand
    {
        public PriceBand()
        {
            SLCustomerAccounts = new HashSet<SLCustomerAccount>();
            SLCustomerPriceMappings = new HashSet<SLCustomerPriceMapping>();
            StockItemPrices = new HashSet<StockItemPrice>();
        }

        public long PriceBandID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool ThisIsTheStandardBand { get; set; }
        public long? CurrencyID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public long? PriceBandTypeID { get; set; }
        public bool? IsActive { get; set; }
        public bool IsTimeBased { get; set; }
        public DateTime? ActiveDateTimeFrom { get; set; }
        public DateTime? ActiveDateTimeTo { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSCurrency Currency { get; set; }
        public virtual PriceBandType PriceBandType { get; set; }
        public virtual ICollection<SLCustomerAccount> SLCustomerAccounts { get; set; }
        public virtual ICollection<SLCustomerPriceMapping> SLCustomerPriceMappings { get; set; }
        public virtual ICollection<StockItemPrice> StockItemPrices { get; set; }
    }
}