// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class ProdGroupSearchCat
    {
        public ProdGroupSearchCat()
        {
            ProdGroupSearchVals = new HashSet<ProdGroupSearchVal>();
        }

        public long ProdGroupSearchCatID { get; set; }
        public long ProductGroupID { get; set; }
        public long SearchCategoryID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ProductGroup ProductGroup { get; set; }
        public virtual SearchCategory SearchCategory { get; set; }
        public virtual ICollection<ProdGroupSearchVal> ProdGroupSearchVals { get; set; }
    }
}