// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class RepIndentedPartsList
    {
        public long ID { get; set; }
        public int? SessionID { get; set; }
        public long? BomID { get; set; }
        public string BomReference { get; set; }
        public string BomDescription { get; set; }
        public decimal BomQty { get; set; }
        public short? Level { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public string Location { get; set; }
        public string ProductCode { get; set; }
        public decimal CostPrice { get; set; }
        public string Notes { get; set; }
        public bool Phantom { get; set; }
        public bool SubAssembly { get; set; }
        public string UnitofMeasure { get; set; }
        public double? Sequence { get; set; }
        public long? CompID { get; set; }
    }
}