// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class RTLPromotion
    {
        public long PromoId { get; set; }
        public string PromoCode { get; set; }
        public string Description { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? RewardValue { get; set; }
        public string LastAmendUser { get; set; }
        public DateTime? LastAmendDateTime { get; set; }
        public long? RewardTypeId { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}