// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class RTLVariantStructure
    {
        public long PrdHierNodeId { get; set; }
        public int Dimes { get; set; }
        public int Dime1 { get; set; }
        public int? Dime2 { get; set; }
        public int? Dime3 { get; set; }
        public string SageProductGroupCode { get; set; }
        public long? DimeSetId1 { get; set; }
        public long? DimeSetId2 { get; set; }
        public long? DimeSetId3 { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}