// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class Sabre_DLP_Current_Transaction_List
    {
        public string AccountCostCentre { get; set; }
        public string AccountDepartment { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public long NLAccountTypeID { get; set; }
        public decimal GoodsValueInBaseCurrency { get; set; }
        public decimal Expr1 { get; set; }
        public decimal Expr2 { get; set; }
        public decimal GoodsValueInDocumentCurrency { get; set; }
        public DateTime TransactionDate { get; set; }
        public string Narrative { get; set; }
        public long NLNominalAccountID { get; set; }
        public DateTime PostedDate { get; set; }
        public long NLPostedNominalTranID { get; set; }
        public string Reference { get; set; }
        public long Source { get; set; }
        public string Name { get; set; }
        public string TransactionAnalysisCode { get; set; }
        public long UniqueReferenceNumber { get; set; }
        public string UserName { get; set; }
        public int UserNumber { get; set; }
    }
}