// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_2018_2019_PGValue
    {
        public string Description { get; set; }
        public decimal? Expr1 { get; set; }
    }
}