// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_BOMOperationTime
    {
        public string AssemblyNo { get; set; }
        public string AssemblyDescription { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public decimal QuantityPerRun { get; set; }
        public int DefaultRunTimeHours { get; set; }
        public byte DefaultRunTimeMinutes { get; set; }
        public byte DefaultRunTimeSeconds { get; set; }
        public int DelayHours { get; set; }
        public byte DelayMinutes { get; set; }
        public byte DelaySeconds { get; set; }
        public decimal? OverlapPercentage { get; set; }
        public decimal? OverlapQuantity { get; set; }
        public decimal? ManningLevel { get; set; }
        public int Hours { get; set; }
        public byte Minutes { get; set; }
        public byte Seconds { get; set; }
        public bool FixedLength { get; set; }
        public decimal FixedLengthQuantity { get; set; }
        public bool PrimaryResource { get; set; }
        public bool SecondaryResource { get; set; }
        public bool ExportToGraphicalPlanner { get; set; }
        public string Code { get; set; }
        public string BomVersion { get; set; }
        public long BomVersionStatusID { get; set; }
    }
}