// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_WO_Expedite
    {
        public string WorksOrderNumber { get; set; }
        public string Status { get; set; }
        public string BomReference { get; set; }
        public string BomDescription { get; set; }
        public decimal QtyRequired { get; set; }
        public decimal QtyFinished { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? DateEntered { get; set; }
        public string CustOrderNumber { get; set; }
        public string LinkedTo { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string EnteredBy { get; set; }
    }
}