// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_ExpediteRole
    {
        public string SupplierAccountNumber { get; set; }
        public string SupplierAccountName { get; set; }
        public string ContactName { get; set; }
        public string ContactValue { get; set; }
        public string PO_Expedite { get; set; }
    }
}