// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_DespatchesByCu
    {
        public short? Y { get; set; }
        public byte? M { get; set; }
        public byte? W { get; set; }
        public string ItemCode { get; set; }
        public decimal? Expr1 { get; set; }
        public string CustomerAccountNumber { get; set; }
    }
}