// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_DownloadReport_TotalBom
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Total { get; set; }
    }
}