// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_ActiveStocktake
    {
        public string StocktakeName { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string BinName { get; set; }
    }
}