// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_DownloadReportWarehouse
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Warehouse { get; set; }
        public decimal ReorderLevel { get; set; }
        public decimal MinimumLevel { get; set; }
        public decimal MaximumLevel { get; set; }
        public DateTime? DateOfLastSale { get; set; }
        public decimal ConfirmedQtyInStock { get; set; }
        public decimal UnconfirmedQtyInStock { get; set; }
        public decimal QuantityAllocatedSOP { get; set; }
        public decimal QuantityAllocatedStock { get; set; }
        public decimal QuantityOnPOPOrder { get; set; }
        public decimal HoldingValueAtBuyPrice { get; set; }
        public DateTime? DateOfLastStockCount { get; set; }
        public decimal PreReceiptAllocationQty { get; set; }
        public decimal QuantityAllocatedBOM { get; set; }
        public decimal QuantityReserved { get; set; }
        public long ItemID { get; set; }
    }
}