// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_OrderLine
    {
        public string DocumentNo { get; set; }
        public string SupplierAccountName { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public DateTime? DocumentDate { get; set; }
        public string DocumentCreatedBy { get; set; }
    }
}