// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_LocationCheck
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string BinName { get; set; }
        public string Description { get; set; }
        public string Expr1 { get; set; }
        public decimal ConfirmedQtyInStock { get; set; }
    }
}