// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_DownloadReportActiveSupplier
    {
        public string SupplierAccountNumber { get; set; }
        public string SupplierAccountName { get; set; }
        public DateTime? DateOfLastTransaction { get; set; }
    }
}