// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_OrdersCreated_Total
    {
        public string Orders_Rasied_BY { get; set; }
        public int? Total_Orders_Rasied { get; set; }
    }
}