// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SABRE_DLP_FACTCON_ST_2014
    {
        public long StocktakeCountShtItemID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string BinName { get; set; }
        public decimal ActualQuantityInStock { get; set; }
    }
}