// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SagePaymentsTransactionStatus
    {
        public SagePaymentsTransactionStatus()
        {
            CBPostedAccountTrans = new HashSet<CBPostedAccountTran>();
        }

        public long SagePaymentsTransactionStatusID { get; set; }
        public string Name { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<CBPostedAccountTran> CBPostedAccountTrans { get; set; }
    }
}