// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SearchCategory
    {
        public SearchCategory()
        {
            ProdGroupSearchCats = new HashSet<ProdGroupSearchCat>();
            SearchValues = new HashSet<SearchValue>();
            StockItemSearchCatVals = new HashSet<StockItemSearchCatVal>();
        }

        public long SearchCategoryID { get; set; }
        public string Name { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<ProdGroupSearchCat> ProdGroupSearchCats { get; set; }
        public virtual ICollection<SearchValue> SearchValues { get; set; }
        public virtual ICollection<StockItemSearchCatVal> StockItemSearchCatVals { get; set; }
    }
}