// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SfdcCurrentlyProcessing
    {
        public long ID { get; set; }
        public long? OpRecNo { get; set; }
        public long? WoRecNo { get; set; }
        public long? JobRecNo { get; set; }
        public long? StgRecNo { get; set; }
        public string EmployeeNumber { get; set; }
        public DateTime? LoggedOn { get; set; }
    }
}