// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SLAgePeriodBalanceView
    {
        public long mmsslapb_CustomerAccountID { get; set; }
        public double? mmsslapb_Balance { get; set; }
        public string mmsslapb_CustomerAccountNumber { get; set; }
        public DateTime mmsslapb_TransactionDate { get; set; }
    }
}