// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SLCustomerPeriodValue
    {
        public long SLCustomerPeriodValueID { get; set; }
        public long SLCustomerAccountID { get; set; }
        public long SLAnalysisPeriodID { get; set; }
        public decimal TotalInvoiceValueToDate { get; set; }
        public decimal TotalCreditNoteValueToDate { get; set; }
        public decimal TotalCashValueToDate { get; set; }
        public decimal TotalProfitValueToDate { get; set; }
        public decimal TotalInvoiceValueToDateInBase { get; set; }
        public decimal TotalCredNoteValueToDateInBase { get; set; }
        public decimal TotalCashValueToDateInBase { get; set; }
        public decimal TotalProfitValueToDateInBase { get; set; }
        public decimal ExchangeRateGainOrLoss { get; set; }
        public decimal TotalFinanceChargesApplied { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SLAnalysisPeriod SLAnalysisPeriod { get; set; }
        public virtual SLCustomerAccount SLCustomerAccount { get; set; }
    }
}