// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SLCustomerSyncStatusType
    {
        public SLCustomerSyncStatusType()
        {
            SLCustomerAccounts = new HashSet<SLCustomerAccount>();
        }

        public long SLCustomerSyncStatusTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SLCustomerAccount> SLCustomerAccounts { get; set; }
    }
}