// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SLSetting
    {
        public long SLSettingID { get; set; }
        public bool CopyStatementsForHeadOffices { get; set; }
        public bool AllowBatchProcessing { get; set; }
        public bool AutoGenerateAccountNumbers { get; set; }
        public int NextAccountNumber { get; set; }
        public bool AllowAdditionalTransAnalysis { get; set; }
        public short EarlySettlementDiscountDays { get; set; }
        public decimal EarlySettlementDiscountPercent { get; set; }
        public short KeepTransactionsFor { get; set; }
        public bool ArchiveTransactionAfterKeeping { get; set; }
        public short BadDebtVATRecoveryWaitPeriod { get; set; }
        public long DefaultSYSTaxRateID { get; set; }
        public short NumberOfAgeingPeriods { get; set; }
        public short DefaultPaymentTermsDays { get; set; }
        public long SYSPaymentTermsBasisID { get; set; }
        public bool UseForeignCurrencyRevaluation { get; set; }
        public long SLTranToShowOnStatementsID { get; set; }
        public long SLDateToUseForAgeingID { get; set; }
        public bool ChargeInterestOnFinanceCharges { get; set; }
        public int NumberOfBatchesThisPeriod { get; set; }
        public bool? UseAccountPeriodsAsTradPeriods { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public bool? DefaultTermsAgreed { get; set; }
        public bool UseCardProcessing { get; set; }
        public bool? ShowOutstandingTrans { get; set; }
        public long MaxEnquiryTransToDisplay { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public bool CaptureAdditionalTransactionDetails { get; set; }

        public virtual SYSTaxRate DefaultSYSTaxRate { get; set; }
        public virtual SLDateToUseForAgeing SLDateToUseForAgeing { get; set; }
        public virtual SLTranToShowOnStatement SLTranToShowOnStatements { get; set; }
        public virtual SYSPaymentTermsBasis SYSPaymentTermsBasis { get; set; }
    }
}