// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SOPOrderReturnType
    {
        public SOPOrderReturnType()
        {
            SOPOrderReturnArchDocumentTypes = new HashSet<SOPOrderReturnArch>();
            SOPOrderReturnArchSourceTypes = new HashSet<SOPOrderReturnArch>();
            SOPOrderReturnDocumentTypes = new HashSet<SOPOrderReturn>();
            SOPOrderReturnSourceTypes = new HashSet<SOPOrderReturn>();
        }

        public long SOPOrderReturnTypeID { get; set; }
        public string SOPOrderReturnTypeName { get; set; }

        public virtual ICollection<SOPOrderReturnArch> SOPOrderReturnArchDocumentTypes { get; set; }
        public virtual ICollection<SOPOrderReturnArch> SOPOrderReturnArchSourceTypes { get; set; }
        public virtual ICollection<SOPOrderReturn> SOPOrderReturnDocumentTypes { get; set; }
        public virtual ICollection<SOPOrderReturn> SOPOrderReturnSourceTypes { get; set; }
    }
}