// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SOPOrderLineProfitAnalysis
    {
        public long SOPOrderLineProfitAnalysisID { get; set; }
        public long SOPOrderProfitAnalysisID { get; set; }
        public long SOPOrderReturnLineID { get; set; }
        public decimal EstimatedCostRate { get; set; }
        public decimal EstProfitPercentOnRev { get; set; }
        public decimal EstProfitPercentOnCost { get; set; }
        public decimal EstimatedProfitValue { get; set; }
        public decimal IssueRate { get; set; }
        public decimal LineQuantity { get; set; }
        public decimal RealisedCostValue { get; set; }
        public decimal RealisedProfitPercentOnCost { get; set; }
        public decimal RealisedProfitPercentOnRev { get; set; }
        public decimal RealisedProfitValue { get; set; }
        public decimal RealisedQuantity { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SOPOrderProfitAnalysis SOPOrderProfitAnalysis { get; set; }
        public virtual SOPOrderReturnLine SOPOrderReturnLine { get; set; }
    }
}