// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SOPOrderReturnArch
    {
        public SOPOrderReturnArch()
        {
            SOPCancelledLineArches = new HashSet<SOPCancelledLineArch>();
            SOPInvCreditLineArches = new HashSet<SOPInvCreditLineArch>();
            SOPOrderReturnLineArches = new HashSet<SOPOrderReturnLineArch>();
            SOPPaymentArches = new HashSet<SOPPaymentArch>();
        }

        public long SOPOrderReturnID { get; set; }
        public long DocumentTypeID { get; set; }
        public string DocumentNo { get; set; }
        public DateTime? DocumentDate { get; set; }
        public long DocumentStatusID { get; set; }
        public long DocumentPrintStatusID { get; set; }
        public string CustomerDocumentNo { get; set; }
        public long CustomerID { get; set; }
        public long CustomerTypeID { get; set; }
        public DateTime? RequestedDeliveryDate { get; set; }
        public DateTime? PromisedDeliveryDate { get; set; }
        public long? WarehouseID { get; set; }
        public long? CurrencyID { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal SubtotalGoodsValue { get; set; }
        public decimal SubtotalChargesNetValue { get; set; }
        public decimal SubtotalChargesTaxValue { get; set; }
        public decimal SubtotalDiscountValue { get; set; }
        public decimal TotalNetValue { get; set; }
        public decimal TotalTaxValue { get; set; }
        public decimal TotalGrossValue { get; set; }
        public bool UseInvoiceAddress { get; set; }
        public bool PaymentWithOrder { get; set; }
        public long PaymentTypeID { get; set; }
        public decimal PaymentValue { get; set; }
        public string PaymentReference { get; set; }
        public long? PaymentBankAccountID { get; set; }
        public string PaymentNominalAccountRef { get; set; }
        public string PaymentNominalCostCentre { get; set; }
        public string PaymentNominalDepartment { get; set; }
        public long? PaymentNominalCodeID { get; set; }
        public bool PaymentInvoiced { get; set; }
        public decimal SettlementDiscPercent { get; set; }
        public short SettlementDiscountDays { get; set; }
        public decimal DocumentDiscountPercent { get; set; }
        public string DocumentCreatedBy { get; set; }
        public string Priority { get; set; }
        public string AnalysisCode1 { get; set; }
        public string AnalysisCode2 { get; set; }
        public string AnalysisCode3 { get; set; }
        public string AnalysisCode4 { get; set; }
        public string AnalysisCode5 { get; set; }
        public string AnalysisCode6 { get; set; }
        public short IntrastatStatus { get; set; }
        public long SourceTypeID { get; set; }
        public string SourceDocumentNo { get; set; }
        public bool ArePricesTaxInclusive { get; set; }
        public bool ReadyForInvoicePrint { get; set; }
        public DateTime? DocumentDueDate { get; set; }
        public long? PaymentMethodID { get; set; }
        public bool BOMDetailsOnDespatchNote { get; set; }
        public string PaymentMethodName { get; set; }
        public decimal TotalGrossValueIncSett { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public string SpareText1 { get; set; }
        public string SpareText2 { get; set; }
        public string SpareText3 { get; set; }
        public decimal SpareNumber1 { get; set; }
        public decimal SpareNumber2 { get; set; }
        public decimal SpareNumber3 { get; set; }
        public DateTime? SpareDate1 { get; set; }
        public DateTime? SpareDate2 { get; set; }
        public DateTime? SpareDate3 { get; set; }
        public bool SpareBit1 { get; set; }
        public bool SpareBit2 { get; set; }
        public bool SpareBit3 { get; set; }
        public string ExternalReference { get; set; }
        public bool InvoicePaymentImmediately { get; set; }
        public string CRMReference { get; set; }
        public long? CRMAccount { get; set; }
        public string AnalysisCode7 { get; set; }
        public string AnalysisCode8 { get; set; }
        public string AnalysisCode9 { get; set; }
        public string AnalysisCode10 { get; set; }
        public string AnalysisCode11 { get; set; }
        public string AnalysisCode12 { get; set; }
        public string AnalysisCode13 { get; set; }
        public string AnalysisCode14 { get; set; }
        public string AnalysisCode15 { get; set; }
        public string AnalysisCode16 { get; set; }
        public string AnalysisCode17 { get; set; }
        public string AnalysisCode18 { get; set; }
        public string AnalysisCode19 { get; set; }
        public string AnalysisCode20 { get; set; }
        public bool TriangularTransaction { get; set; }
        public DateTime DateTimeUpdated { get; set; }
        public bool ReadyForAllocation { get; set; }
        public long AllocatedStatusID { get; set; }
        public bool ReadyForDespatchReceipt { get; set; }
        public long DespatchReceiptStatusID { get; set; }
        public long InvoiceCreditStatusID { get; set; }
        public long CancelledStatusID { get; set; }
        public bool IsCIS { get; set; }

        public virtual DocumentProcessStatus AllocatedStatus { get; set; }
        public virtual DocumentProcessStatus CancelledStatus { get; set; }
        public virtual SYSCurrency Currency { get; set; }
        public virtual SLCustomerAccount Customer { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual DocumentProcessStatus DespatchReceiptStatus { get; set; }
        public virtual DocumentPrintStatus DocumentStatus { get; set; }
        public virtual DocumentStatus DocumentStatusNavigation { get; set; }
        public virtual SOPOrderReturnType DocumentType { get; set; }
        public virtual DocumentProcessStatus InvoiceCreditStatus { get; set; }
        public virtual CBAccount PaymentBankAccount { get; set; }
        public virtual SOPPaymentMethod PaymentMethod { get; set; }
        public virtual NLNominalAccount PaymentNominalCode { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual SOPOrderReturnType SourceType { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual CashAcctInvAddressArch CashAcctInvAddressArch { get; set; }
        public virtual SOPDocDelAddressArch SOPDocDelAddressArch { get; set; }
        public virtual ICollection<SOPCancelledLineArch> SOPCancelledLineArches { get; set; }
        public virtual ICollection<SOPInvCreditLineArch> SOPInvCreditLineArches { get; set; }
        public virtual ICollection<SOPOrderReturnLineArch> SOPOrderReturnLineArches { get; set; }
        public virtual ICollection<SOPPaymentArch> SOPPaymentArches { get; set; }
    }
}