// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SOPProspectQuoteSettingView
    {
        public long mmspqs_SOPSettingID { get; set; }
        public bool mmspqs_AllowProspectQuoted { get; set; }
        public long? mmspqs_ProspectQuoteAccountID { get; set; }
    }
}