// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SOPProductsPurchasedView
    {
        public long mmssopp_TransactionHistoryID { get; set; }
        public long mmssopp_TransactionTypeID { get; set; }
        public DateTime mmssopp_TransactionDate { get; set; }
        public double? mmssopp_Quantity { get; set; }
        public string mmssopp_Code { get; set; }
        public string mmssopp_Name { get; set; }
        public double? mmssopp_IssueValue { get; set; }
        public DateTime? mmssopp_PostedDate { get; set; }
        public string mmssopp_SourceAreaReference { get; set; }
        public string mmssopp_StockItemID { get; set; }
        public string mmssopp_StockItemStatusName { get; set; }
        public double? mmssopp_UnitCostPrice { get; set; }
        public double? mmssopp_UnitIssuePrice { get; set; }
        public double? mmssopp_UnitDiscountValue { get; set; }
        public double? mmssopp_TotalOrderDiscount { get; set; }
        public double? mmssopp_CostValue { get; set; }
    }
}