// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SOPReturnNumber
    {
        public long SOPReturnNumberID { get; set; }
        public long NextSOPReturnNumber { get; set; }
    }
}