// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SOPUserPermission
    {
        public SOPUserPermission()
        {
            UserDefaultWarehouses = new HashSet<UserDefaultWarehouse>();
        }

        public long SOPUserPermissionID { get; set; }
        public long SOPUserID { get; set; }
        public bool OverridePricesDiscounts { get; set; }
        public bool ViewProfitValues { get; set; }
        public bool ViewPriceCalculations { get; set; }
        public bool OverrideCreditHolds { get; set; }
        public bool OverrideFulfilmentMethod { get; set; }
        public bool OverrideConfirmationMethod { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public bool OverrideCostPrice { get; set; }
        public bool GeneratePurchaseOrders { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SOPUser SOPUser { get; set; }
        public virtual ICollection<UserDefaultWarehouse> UserDefaultWarehouses { get; set; }
    }
}