// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class STItemSuppliersView
    {
        public string mmssts_Code { get; set; }
        public string mmssts_SupplierAccountName { get; set; }
        public double? mmssts_QuantityOnOrder { get; set; }
        public string mmssts_Name { get; set; }
        public string mmssts_SupplierAccountNumber { get; set; }
        public long mmssts_ItemID { get; set; }
        public string mmssts_LeadTime { get; set; }
        public string mmssts_Preferred { get; set; }
    }
}