// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class STKProductStockItemSupplierView
    {
        public long? StockItemSupplierID { get; set; }
        public long? SupplierLandedCostsTypeID { get; set; }
        public decimal? SupplierLandedCostsValue { get; set; }
        public long StockLandedCostsTypeID { get; set; }
        public decimal StockLandedCostsValue { get; set; }
        public long ProductGroupID { get; set; }
    }
}