// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class STKStocktakeCriteriaTemplate
    {
        public long STKStocktakeCriteriaTemplateID { get; set; }
        public string CriteriaName { get; set; }
        public string Criteria { get; set; }
    }
}