// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class STKTraceItemBatchAttribute
    {
        public long STKTraceItemBatchAttributeID { get; set; }
        public long TraceableItemID { get; set; }
        public string Title { get; set; }
        public string Value { get; set; }
        public bool IsCompulsory { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual TraceableItem TraceableItem { get; set; }
    }
}