// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class STKWorkspaceStockItem
    {
        public decimal QuantityInStock { get; set; }
        public decimal QuantityAllocated { get; set; }
        public decimal QuantityOnPOPOrder { get; set; }
        public decimal SalesPrice { get; set; }
        public long ItemID { get; set; }
        public long ProductGroupID { get; set; }
        public string ProductGroupCode { get; set; }
        public string ProductGroupName { get; set; }
        public string StockItemType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StockItemStatusName { get; set; }
        public DateTime? InactiveDate { get; set; }
        public string StockUnitName { get; set; }
        public string TaxRate { get; set; }
        public string CostingMethod { get; set; }
        public decimal StandardCost { get; set; }
        public decimal AverageBuyingPrice { get; set; }
        public decimal FreeStockQuantity { get; set; }
        public decimal QtySoldThisPeriod { get; set; }
        public decimal ValSoldThisPeriod { get; set; }
        public decimal QtySoldLastPeriod { get; set; }
        public decimal ValSoldLastPeriod { get; set; }
        public decimal QtyBoughtThisPeriod { get; set; }
        public decimal ValBoughtThisPeriod { get; set; }
        public decimal QtyBoughtLastPeriod { get; set; }
        public decimal ValBoughtLastPeriod { get; set; }
        public string TraceableType { get; set; }
        public string Manufacturer { get; set; }
        public string PartNumber { get; set; }
        public string BOMDetails { get; set; }
        public string LabelPrintingOption { get; set; }
        public bool AllowSalesOrder { get; set; }
        public string CommodityCode { get; set; }
        public decimal Weight { get; set; }
        public bool IsWEEEItem { get; set; }
        public bool UsesSupplementaryUnit { get; set; }
        public bool SuppressNetMass { get; set; }
        public decimal SupplementaryUnitConversionRatio { get; set; }
        public bool UsesRCV { get; set; }
        public string CountryOfOrigin { get; set; }
        public short StocktakeCyclePeriod { get; set; }
        public string LandedCosts { get; set; }
    }
}