// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSAccountingModulePermiss
    {
        public long SYSAccountingModulePermissID { get; set; }
        public long SYSAccountingPeriodPermissID { get; set; }
        public long SYSModuleID { get; set; }
        public bool CanOpen { get; set; }
        public bool CanClose { get; set; }
        public bool CanReOpen { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSAccountingPeriodPermiss SYSAccountingPeriodPermiss { get; set; }
        public virtual SYSModule SYSModule { get; set; }
    }
}