// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSCreditPosition
    {
        public SYSCreditPosition()
        {
            PLSupplierAccounts = new HashSet<PLSupplierAccount>();
            SLCustomerAccounts = new HashSet<SLCustomerAccount>();
        }

        public long SYSCreditPositionID { get; set; }
        public string Name { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public bool IsDefault { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<PLSupplierAccount> PLSupplierAccounts { get; set; }
        public virtual ICollection<SLCustomerAccount> SLCustomerAccounts { get; set; }
    }
}