// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSExchangeRateHistory
    {
        public long SYSExchangeRateHistoryID { get; set; }
        public long SYSCurrencyID { get; set; }
        public long SYSExchangeRateActionID { get; set; }
        public string PreviousValue { get; set; }
        public string NewValue { get; set; }
        public string UserName { get; set; }
        public DateTime DateAndTimeActionPerformed { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSCurrency SYSCurrency { get; set; }
        public virtual SYSExchangeRateAction SYSExchangeRateAction { get; set; }
    }
}