// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSExchangeRateType
    {
        public SYSExchangeRateType()
        {
            PLPendSupplierAccounts = new HashSet<PLPendSupplierAccount>();
            PLSupplierAccounts = new HashSet<PLSupplierAccount>();
            SLCustomerAccounts = new HashSet<SLCustomerAccount>();
            SLPendCustomerAccounts = new HashSet<SLPendCustomerAccount>();
            SYSCurrencies = new HashSet<SYSCurrency>();
        }

        public long SYSExchangeRateTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<PLPendSupplierAccount> PLPendSupplierAccounts { get; set; }
        public virtual ICollection<PLSupplierAccount> PLSupplierAccounts { get; set; }
        public virtual ICollection<SLCustomerAccount> SLCustomerAccounts { get; set; }
        public virtual ICollection<SLPendCustomerAccount> SLPendCustomerAccounts { get; set; }
        public virtual ICollection<SYSCurrency> SYSCurrencies { get; set; }
    }
}