// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSInformationView
    {
        public string Entity { get; set; }
        public string Value { get; set; }
    }
}