// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSModulePostingStatus
    {
        public SYSModulePostingStatus()
        {
            SYSModuleAccountingPeriods = new HashSet<SYSModuleAccountingPeriod>();
        }

        public long SYSModulePostingStatusID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SYSModuleAccountingPeriod> SYSModuleAccountingPeriods { get; set; }
    }
}