// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSPeriodExchangeRate
    {
        public long SYSPeriodExchangeRate1 { get; set; }
        public long SYSCurrencyID { get; set; }
        public byte CurrencyType { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public decimal OneUnitEquals { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSCurrency SYSCurrency { get; set; }
    }
}