// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSSupportLog
    {
        public long SYSSupportLogID { get; set; }
        public string FormName { get; set; }
        public string UserName { get; set; }
        public DateTime DateTimeOfOpen { get; set; }
        public DateTime DateTimeOfClose { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}