// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class SYSTaxECTerm
    {
        public SYSTaxECTerm()
        {
            SYSTaxRates = new HashSet<SYSTaxRate>();
        }

        public long SYSTaxECTermID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SYSTaxRate> SYSTaxRates { get; set; }
    }
}