// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TEMStandardTaxCode
    {
        public TEMStandardTaxCode()
        {
            TEMTaxCodeMappings = new HashSet<TEMTaxCodeMapping>();
        }

        public long TEMStandardTaxCodeID { get; set; }
        public string Name { get; set; }
        public long? CountryCodeID { get; set; }
        public long TEMCodePageID { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual SYSCountryCode CountryCode { get; set; }
        public virtual ICollection<TEMTaxCodeMapping> TEMTaxCodeMappings { get; set; }
    }
}