// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TraceableTransType
    {
        public TraceableTransType()
        {
            TraceableTransArchives = new HashSet<TraceableTransArchive>();
            TraceableTransHistories = new HashSet<TraceableTransHistory>();
        }

        public long TraceableTransTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<TraceableTransArchive> TraceableTransArchives { get; set; }
        public virtual ICollection<TraceableTransHistory> TraceableTransHistories { get; set; }
    }
}