// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TSExpensesConfiguration
    {
        public long TSExpensesConfigurationID { get; set; }
        public bool? AllowExpenseEntry { get; set; }
        public long NextExpenseClaimNumber { get; set; }
        public bool RequireExpenseAuthorisation { get; set; }
        public bool UseExpenseCategories { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }
    }
}