// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TSExpensesRecordStatusType
    {
        public TSExpensesRecordStatusType()
        {
            TSExpensesRecordSheetStatuses = new HashSet<TSExpensesRecordSheetStatus>();
        }

        public long TSExpensesRecordStatusTypeID { get; set; }
        public string Description { get; set; }

        public virtual ICollection<TSExpensesRecordSheetStatus> TSExpensesRecordSheetStatuses { get; set; }
    }
}