// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TSPaymentMethod
    {
        public TSPaymentMethod()
        {
            TSClaimSheets = new HashSet<TSClaimSheet>();
            TSHumanResources = new HashSet<TSHumanResource>();
        }

        public long TSPaymentMethodID { get; set; }
        public string Description { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual ICollection<TSClaimSheet> TSClaimSheets { get; set; }
        public virtual ICollection<TSHumanResource> TSHumanResources { get; set; }
    }
}