// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TSResourceHierarchy
    {
        public TSResourceHierarchy()
        {
            InverseParentHierarchy = new HashSet<TSResourceHierarchy>();
            TSResourceChargeRateLinks = new HashSet<TSResourceChargeRateLink>();
            TSResourceCostRateLinks = new HashSet<TSResourceCostRateLink>();
            TSResourceHierarchyPeople = new HashSet<TSResourceHierarchyPerson>();
        }

        public long TSResourceHierarchyID { get; set; }
        public string Description { get; set; }
        public long? ParentHierarchyID { get; set; }
        public long TSResourceHierarchyItemTypeID { get; set; }
        public long TSResourceTypeID { get; set; }
        public string Name { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual TSResourceHierarchy ParentHierarchy { get; set; }
        public virtual TSResourceHierarchyItemType TSResourceHierarchyItemType { get; set; }
        public virtual TSResourceType TSResourceType { get; set; }
        public virtual ICollection<TSResourceHierarchy> InverseParentHierarchy { get; set; }
        public virtual ICollection<TSResourceChargeRateLink> TSResourceChargeRateLinks { get; set; }
        public virtual ICollection<TSResourceCostRateLink> TSResourceCostRateLinks { get; set; }
        public virtual ICollection<TSResourceHierarchyPerson> TSResourceHierarchyPeople { get; set; }
    }
}