// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TSSubmissionFrequencyType
    {
        public TSSubmissionFrequencyType()
        {
            TSTimesheetClientConfigs = new HashSet<TSTimesheetClientConfig>();
        }

        public long SubmissionFrequencyTypeID { get; set; }
        public string Description { get; set; }

        public virtual ICollection<TSTimesheetClientConfig> TSTimesheetClientConfigs { get; set; }
    }
}