// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TSTimeFinancialsIntegration
    {
        public long TSFinancialsIntegrationID { get; set; }
        public bool IsIntegrated { get; set; }
        public bool PostAutomatically { get; set; }
        public long TSPostingMethodID { get; set; }
        public bool EnterNominalAccOnTimesheet { get; set; }
        public byte[] OpLock { get; set; }
        public DateTime DateTimeCreated { get; set; }
        public string DefaultNominalAccountNumber { get; set; }
        public string DefaultNominalAccountCostCentre { get; set; }
        public string DefaultNominalAccountDepartment { get; set; }
        public string NominalControlAccountNumber { get; set; }
        public string NominalControlAccountCostCentre { get; set; }
        public string NominalControlAccountDepartment { get; set; }
        public DateTime DateTimeUpdated { get; set; }

        public virtual TSPostingMethodType TSPostingMethod { get; set; }
    }
}