// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class TSTimesheetPostStatusType
    {
        public TSTimesheetPostStatusType()
        {
            TSTimesheetPostStatusTSPostedToFinancialsStatuses = new HashSet<TSTimesheetPostStatus>();
            TSTimesheetPostStatusTSPostedToProjCostStatuses = new HashSet<TSTimesheetPostStatus>();
        }

        public long TSPostedStatusTypeID { get; set; }
        public string Name { get; set; }

        public virtual ICollection<TSTimesheetPostStatus> TSTimesheetPostStatusTSPostedToFinancialsStatuses { get; set; }
        public virtual ICollection<TSTimesheetPostStatus> TSTimesheetPostStatusTSPostedToProjCostStatuses { get; set; }
    }
}