// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_DashboardWoBeingProcessed
    {
        public long WoID { get; set; }
        public string WorksOrderNumber { get; set; }
        public string Reference { get; set; }
        public int OneOff { get; set; }
        public decimal? WipValue { get; set; }
        public decimal? SalesValue { get; set; }
        public decimal? QtyOutstanding { get; set; }
        public string Description { get; set; }
    }
}