// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_EstTransReport
    {
        public long? EstID { get; set; }
        public long? StageID { get; set; }
        public string RecordType { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public decimal CostPrice { get; set; }
        public decimal Total { get; set; }
        public string UnitOfSale { get; set; }
        public decimal LabourTotal { get; set; }
        public decimal MachineTotal { get; set; }
        public decimal SetupTotal { get; set; }
        public decimal ToolingTotal { get; set; }
        public decimal SubContTotal { get; set; }
    }
}