// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_RepBomComponent
    {
        public long ID { get; set; }
        public long? BomID { get; set; }
        public double? Sequence { get; set; }
        public string StockCode { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public decimal? Quantity { get; set; }
        public string Instruction { get; set; }
        public string UnitofMeasure { get; set; }
        public string BulkIssueItem { get; set; }
        public double ScrapPercent { get; set; }
        public string Private { get; set; }
        public string HoldQuantity { get; set; }
    }
}