// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_RepWorkToHeader
    {
        public long WoID { get; set; }
        public string WorksOrderNumber { get; set; }
        public string BomReference { get; set; }
        public string BomDescription { get; set; }
        public string Notes { get; set; }
        public DateTime? DateEntered { get; set; }
        public string PlanReference { get; set; }
        public string Status { get; set; }
        public decimal? QtyRequired { get; set; }
        public decimal? QtyOutstanding { get; set; }
        public decimal? QtyCompleted { get; set; }
        public string ProjectNumber { get; set; }
        public string WorksNumber { get; set; }
        public short? PcntComplete { get; set; }
        public string AnalysisCode_1 { get; set; }
        public string AnalysisCode_2 { get; set; }
        public string AnalysisCode_3 { get; set; }
        public string AnalysisCode_4 { get; set; }
        public string AnalysisCode_5 { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public DateTime? StartDateNoFormat { get; set; }
        public DateTime? EndDateNoFormat { get; set; }
    }
}