// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_RepSubstituteTraceableAudit
    {
        public string WorksOrderNumber { get; set; }
        public string BomReference { get; set; }
        public string FinishedItemTraceableIdentificationNo { get; set; }
        public string StockCode { get; set; }
        public string ComponentIdentificationNo { get; set; }
        public decimal? Qty { get; set; }
        public string ActionDescription { get; set; }
        public string LoggedOnUser { get; set; }
        public DateTime? PerformedOn { get; set; }
        public string MovementType { get; set; }
    }
}