// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_SubContractStockAtSubContractor
    {
        public string WorksOrderNumber { get; set; }
        public double? Sequence { get; set; }
        public string OpReference { get; set; }
        public string OpDescription { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public string SupplierRef { get; set; }
        public decimal? QtyAtSubContractor { get; set; }
        public string Source { get; set; }
        public decimal? UnitCost { get; set; }
        public decimal? Value { get; set; }
    }
}