// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_SubContractRaisePurchaseOrder
    {
        public long OpID { get; set; }
        public string WorksOrderNumber { get; set; }
        public string BomReference { get; set; }
        public string BomDescription { get; set; }
        public double? Sequence { get; set; }
        public string OpReference { get; set; }
        public string OpDescription { get; set; }
        public decimal? Required { get; set; }
        public decimal? Despatched { get; set; }
        public decimal? Ordered { get; set; }
        public decimal? Completed { get; set; }
        public string Source { get; set; }
        public string SubContDetails { get; set; }
        public string Narrative { get; set; }
        public string Supplier { get; set; }
        public DateTime? StartDate { get; set; }
        public int? LeadTime { get; set; }
        public decimal? CostPrice { get; set; }
        public decimal? ToBeOrdered { get; set; }
        public long WoID { get; set; }
        public long JobID { get; set; }
        public long StageID { get; set; }
        public long? WarehouseID { get; set; }
    }
}