// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class vw_WoWorkInProgressAllCost
    {
        public long WoID { get; set; }
        public string WorksOrderNumber { get; set; }
        public string BomReference { get; set; }
        public decimal QtyRequired { get; set; }
        public decimal? QtyOutstanding { get; set; }
        public decimal QtyFinished { get; set; }
        public decimal? ActMaterialCost { get; set; }
        public decimal ActLabourCost { get; set; }
        public decimal ActMachineCost { get; set; }
        public decimal ActSetupCost { get; set; }
        public decimal ActToolingCost { get; set; }
        public decimal ActSubContCost { get; set; }
        public decimal ActOtherCost { get; set; }
        public decimal ActStdMatCost { get; set; }
        public decimal? ActTotalCost { get; set; }
        public string AnalysisCode_1 { get; set; }
        public string AnalysisCode_2 { get; set; }
        public string AnalysisCode_3 { get; set; }
        public string AnalysisCode_4 { get; set; }
        public string AnalysisCode_5 { get; set; }
    }
}