// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class WarehouseType
    {
        public WarehouseType()
        {
            Warehouses = new HashSet<Warehouse>();
        }

        public long WarehouseTypeID { get; set; }
        public string WarehouseTypeName { get; set; }

        public virtual ICollection<Warehouse> Warehouses { get; set; }
    }
}