// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class Workspaces_ContentPartFilter
    {
        public long ContentPartFilterID { get; set; }
        public string ContentPartID { get; set; }
        public string Name { get; set; }
        public string Filters { get; set; }
        public string Version { get; set; }
        public long UserID { get; set; }
    }
}