// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Titan.API.Models
{
    public partial class WTEProjectItemExpenseSearchView
    {
        public long? PCProjectItemID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
    }
}